#+TITLE: Makefile
#+AUTHOR: Timothy Daly
** Notes
Notes for understanding this makefile:

IMPORTANT: all source file names in this Makefile must be lowercase
This is for cross-platform compatibility and also makes getting
them into Lisp much easier at the Makefile level.

** The Environment
We define 4 directories for this build. The first three are
the traditional *IN*, which is where the source pamphlets are,
*MID* which is where we will put the compiled intermediates and
*OUT* which is where we will put the binaries.

In this case the *IN* files are usually written in *boot* [cite:@2].
These will be compiled in a *BOOTSYS* image to translate from
*boot* to Common Lisp. Since the Common Lisp code is 
system independent and machine generated code the *MID* directory
is built in the *\$SPAD/int* subtree. See the 
*\$SPAD/Makefile.pamphlet* [cite:@1] file for more details.

The Common Lisp code will be compiled from the *MID* directory
into the *OUT* directory. This is system-dependent,
machine-generated code and belongs in the *\$SPAD/obj* subtree.

The dvi files will be generated from the pamphlet files in the
final ship doc/src/ directory. Since they are system independent 
but machine generated and part of the final ship they will exist 
in *\$SPAD/mnt/sys/doc/src/interp*.

#+NAME: environment
#+begin_src common-lisp :noweb yes
IN=${SRC}/interp
MID=${INT}/interp
OUT=${OBJ}/${SYS}/interp
DOC=${MNT}/${SYS}/doc/src/interp
BOOK=${MNT}/${SYS}/doc

#+end_src

In order to minimize the size of the Axiom image at load time
we put some of the compiled files into a separate directory
that will be autoloaded on demand. This directory of code
will be shipped with the final system and so it belongs in
the *\$SPAD/mnt* subtree.
#+NAME: environment
#+begin_src common-lisp :noweb yes
AUTO=${MNT}/${SYS}/autoload

#+end_src

We need a raw lisp image that we can use as a base to construct
the other images. This is called *LISPSYS* and is 
system-dependent and machine-generated.
It belongs in the *\$SPAD/obj* subtree.
#+NAME: environment
#+begin_src common-lisp :noweb yes
LISPSYS= ${OBJ}/${SYS}/bin/lisp

#+end_src

We need to extract the Numerics chunk from bookvol10.5. We do 
this using the tangle function in the lisp image.
#+NAME: environment
#+begin_src common-lisp :noweb yes
LISPTANGLE= ${OBJ}/${SYS}/bin/lisp

#+end_src

Most of the interpreter is written in *boot* [cite:@2].
Thus we need a program to translate *boot* to Common
Lisp. This is called the *BOOTSYS* image (because the
translator is written in *boot* and needs to translate
itself to bootstrap the system). This image is assumed to
have been built by a previous step in the make process.
#+NAME: environment
#+begin_src common-lisp :noweb yes
BOOTSYS= ${OBJ}/${SYS}/bin/bootsys    

#+end_src

Some of the Common Lisp code we compile uses macros which
are assumed to be available at compile time. The *DEPSYS*
image is created to contain the compile time environment
and saved. We pipe compile commands into this environment
to compile from Common Lisp to machine dependent code.

#+NAME: environment
#+begin_src common-lisp :noweb yes
DEPSYS=	${OBJ}/${SYS}/bin/depsys

#+end_src

The *DEP* variable contains the list of files that
will be loaded into *DEPSYS*. Notice that these files
are loaded in interpreted form. We are not concerned about
the compile time performance so we can use interpreted code.
We do, however, care about the macros as these will be
expanded in later compiles. All macros are assumed to be
in this list of files.
#+NAME: environment
#+begin_src common-lisp :noweb yes
DEP= ${MID}/vmlisp.lisp

#+end_src

Once we've compile all of the Common Lisp files we fire up
a clean lisp image called *LOADSYS*, load all of the
final executable code and save it out as *SAVESYS*.
The *SAVESYS* image is copied to the =${MNT}/${SYS}/bin=
subdirectory and becomes the axiom executable image.
#+NAME: environment
#+begin_src common-lisp :noweb yes
LOADSYS= ${OBJ}/${SYS}/bin/lisp
SAVESYS= ${OBJ}/${SYS}/bin/interpsys
AXIOMSYS= ${MNT}/${SYS}/bin/AXIOMsys

#+end_src

Occasionally we need to really get into the system internals.
The best way to do this is to run almost all of the lisp code
interpreted rather than compiled (note that cfuns.lisp and sockio.lisp
still need to be loaded in compiled form as they depend on the 
loader to link with lisp internals). This image is nothing more
than a load of the file src/interp/debugsys.lisp.pamphlet. If
you need to make test modifications you can add code to that
file and it will show up here.
#+NAME: environment
#+begin_src common-lisp :noweb yes
DEBUGSYS=${OBJ}/${SYS}/bin/debugsys

#+end_src

These are the files that need to be compiled (in *BOOTSYS*),
loaded into a clean lisp image (*LOADSYS*) and saved as
a runnable Axiom interpreter (*SAVESYS*) usually named
*interpsys*. Most of these files
are translated from *boot* to Common Lisp and then 
compiled. There are two exceptions, *bootfuns.lisp*
and *setq.lisp*. The *bootfuns.lisp* [cite:@3] file
contains forward references for *boot* code. The *setq.lisp*
file contains constant initialization code which gains nothing
by being compiled.

The file http.lisp contains code to enable browser-based hyperdoc
and graphics.
#+NAME: environment
#+begin_src common-lisp :noweb yes
OBJS= ${OUT}/vmlisp.${O}      \
      ${OUT}/buildom.${O} \
      ${OUT}/cattable.${O}    \
      ${OUT}/cfuns.${O} \
      ${OUT}/clam.${O}	${OUT}/clammed.${O} \
      ${OUT}/compress.${O} \
      ${OUT}/format.${O} \
      ${OUT}/g-boot.${O}      ${OUT}/g-cndata.${O} \
      ${OUT}/g-error.${O}     \
      ${OUT}/g-timer.${O}     ${OUT}/g-util.${O} \
      ${OUT}/http.${O} \
      ${OUT}/hypertex.${O}    ${OUT}/i-analy.${O} \
      ${OUT}/i-code.${O}      ${OUT}/i-coerce.${O} \
      ${OUT}/i-coerfn.${O}    ${OUT}/i-eval.${O} \
      ${OUT}/i-funsel.${O}    ${OUT}/bookvol5.${O} \
      ${OUT}/bookvol9.${O}    ${OUT}/bookvol10.5.${O}\
      ${OUT}/i-intern.${O}    ${OUT}/i-map.${O} \
      ${OUT}/i-output.${O}    ${OUT}/i-resolv.${O} \
      ${OUT}/i-spec1.${O}    \
      ${OUT}/i-spec2.${O}    \
      ${OUT}/i-util.${O} \
      ${OUT}/lisplib.${O}  \
      ${OUT}/match.${O}    \
      ${OUT}/msgdb.${O}    \
      ${OUT}/newfort.${O} \
      ${OUT}/nrunfast.${O} \
      ${OUT}/nrungo.${O}      ${OUT}/nrunopt.${O} \
      ${OUT}/posit.${O}       \
      ${OUT}/record.${O}      \
      ${OUT}/rulesets.${O} \
      ${OUT}/server.${O}    \
      ${OUT}/simpbool.${O}    ${OUT}/slam.${O} \
      ${OUT}/sockio.${O}      \
      ${OUT}/template.${O}    ${OUT}/termrw.${O} \
      ${OUT}/fortcall.${O} \
      ${OUT}/parsing.${O}  \
      ${OUT}/c-util.${O}      ${OUT}/profile.${O}  \
      ${OUT}/category.${O}    \
      ${OUT}/functor.${O}  \
      ${OUT}/info.${O}	${OUT}/iterator.${O} \
      ${OUT}/nruncomp.${O} 

#+end_src

#+begin_example
      sfsfun.lisp.pamphlet contains 0F1 code
#+end_example

Before we save the *SAVESYS* image we need to run some
initialization code. These files perform initialization
for various parts of the system. The *patches.lisp* [cite:@5]
file contains last-minute changes to various functions and
constants.
#+NAME: environment
#+begin_src common-lisp :noweb yes
INOBJS=	 ${OUT}/patches.${O}

#+end_src

Certain functions do not need to be in the running system.
If the running image never calls the compiler or does not
use the hypertex browser we will never call the functions
in these files. The code that calls these functions in the
running system will autoload the appropriate files the
first time they are called. Loading the files overwrites
the autoload function call and re-calls the function. 
Any subsequent calls will run the compiled code.

The *OPOBJS* list contains files from the old parser. The use of
``old'' is something of a subtle concept as there were several
generations of ``old'' and all meaning of the term is lost.

#+NAME: environment
#+begin_src common-lisp :noweb yes
# These are autloaded old parser files
OPOBJS=	
#+end_src

The *OCOBJS* list contains files from the old compiler. Again,
``old'' is meaningless. These files should probably be autoloaded.
#+NAME: environment
#+begin_src common-lisp :noweb yestpdhere
OCOBJS=	
#+end_src

The *BROBJS* list contains files only used by the hypertex
browser. These files should probably be autoloaded.
#+NAME: environment
#+begin_src common-lisp :noweb yes
BROBJS=	${AUTO}/br-con.${O}	\
	${AUTO}/topics.${O}     

#+end_src

The *NAGBROBJS* list contains files used to access the 
Numerical Algorithms Group (NAG) fortran libraries. 
These files should probably be autoloaded.
Note that =${AUTO}/nag-e02a.${O}= is not included in this
list as it is a subset of =${AUTO}/nag-e02.${O}=.
#+NAME: environment
#+begin_src common-lisp :noweb yes
NAGBROBJS= ${AUTO}/nag-c02.${O}   ${AUTO}/nag-c05.${O} \
	   ${AUTO}/nag-c06.${O}   ${AUTO}/nag-d01.${O} \
	   ${AUTO}/nag-d02.${O}   ${AUTO}/nag-d03.${O} \
	   ${AUTO}/nag-e01.${O}   ${AUTO}/nag-e02.${O} \
	   ${AUTO}/nag-e04.${O}   ${AUTO}/nag-f01.${O} \
	   ${AUTO}/nag-f02.${O}   ${AUTO}/nag-f04.${O} \
	   ${AUTO}/nag-f07.${O}   ${AUTO}/nag-s.${O} 

#+end_src
The *ASCOMP* list contains files used by the *Aldor*
[cite:@5] compiler. These files should probably be autoloaded.
#+NAME: environment
#+begin_src common-lisp :noweb yes
ASCOMP= ${OUT}/hashcode.${O}

#+end_src

Axiom versions are given as a string of the form:
"Sunday September 21, 2003 at 20:38:05 "
which describe the day, date, and time of the build.
This is used for reporting bugs. It is only partially useful
in identifying which source code was used. Ideally we could create
a tar file of all of the date/time stamps of all of the source files
and use the MD5 hash of that file as the version stamp. Ultimately
though, this would be chasing the elusive "perfect information" idea.

A new variable =boot::*build-version*= is set and used by the
=yearweek= function to display the version number of the Axiom build.
This information is set by hand in the top level Makefile.
#+NAME: environment
#+begin_src common-lisp :noweb yes
TIMESTAMP=${MNT}/${SYS}/timestamp
YEARWEEK=(progn (setq timestamp "${TIMESTAMP}") \
		(setq boot::*build-version* "${VERSION}") \
		(yearweek))

#+end_src
The *.PRECIOUS* setting will keep make from deleting these
images if the build is stopped. Since once they are built they
are likely to be useable we don't need to redo the work if they
exist.
#+NAME: environment
#+begin_src common-lisp :noweb yes

.PRECIOUS:	${BOOTSYS}
.PRECIOUS:	${DEPSYS}
.PRECIOUS:	${SAVESYS}
.PRECIOUS:	${AXIOMSYS}

#+end_src
** Proclaim optimization
GCL, and possibly other common lisps, can generate much better
code if the function argument types and return values are proclaimed.

In theory what we should do is scan all of the functions in the system
and create a file of proclaim definitions. These proclaim definitions
should be loaded into the image before we do any compiles so they can
allow the compiler to optimize function calling.

GCL has an approximation to this scanning which we use here. 

The first step is to build a version of GCL that includes =gcl_collectfn=.
This file contains code that enhances the lisp compiler and creates a
hash table of structs. Each struct in the hash table describes information
that about the types of the function being compiled and the types of its
arguments. At the end of the compile-file this hash table is written out
to a ".fn" file. 

The second step is to build axiom images (depsys, interpsys, AXIOMsys)
which contain the =gcl_collectfn= code.

The third step is to build the system. This generates a .fn file for 
each lisp file that gets compiled.

The fourth step is to build the proclaims.lisp files. There is one
proclaims.lisp file for 
boot (boot-proclaims.lisp), 
interp (interp-proclaims.lisp), and 
algebra (algebra-proclaims.lisp).

To build the proclaims file (e.g. for interp) we:
#+begin_example
(a) cd to obj/linux/interp
(b) (yourpath)/axiom/obj/linux/bin/lisp
(c) (load "sys-pkg.lsp") 
(d) (mapcar #'load (directory "*.fn"))
(e) (with-open-file 
     (out "interp-proclaims.lisp" :direction :output) 
      (compiler::make-proclaims out))
#+end_example
Note that step (c) is only used for interp, not for boot.

The fifth step is to copy the newly constructed proclaims file back
into the src/interp diretory (or boot, algebra).

In order for this information to be used during compiles we define
the PROCLAIMS form. Under *LISPFLAVOR=sbcl* the proclaims file is
not loaded: it was generated by GCL's compiler::make-proclaims and
contains GCL-dialect type specifiers --- the very first entry declares
=(FTYPE (FUNCTION (*) ...))=, and ANSI has no =(*)=
argument-list form, so SBCL rejects the file at the first proclaim
(observed, not assumed). Proclaims are compilation /hints/; the
system is semantically whole without them, only somewhat slower to
run. The package definitions in sys-pkg.lsp, which the same form
loads first, are load-bearing on every host and are kept.
Regenerating an ANSI-clean proclaims file for SBCL is deferred as a
later optimization.
#+NAME: environment
#+begin_src common-lisp :noweb yes
ifeq (${LISPFLAVOR},sbcl)
PROCLAIMS=(progn (load "${OUT}/sys-pkg.lsp"))
else
PROCLAIMS=(progn (load "${OUT}/sys-pkg.lsp") \
		 (load "${IN}/interp-proclaims.lisp"))
endif

#+end_src

** The warm.data file
This is a file of commands that will be loaded into interpsys
at the last minute. It execute functions that will likely be
used in a running system so all of the required routines will
be in the lisp image thus minimizing their startup time.
#+NAME: warm.data.stanza
#+begin_src common-lisp :noweb yes
${INT}/algebra/warm.data: 
	@ echo si001 building warm.data
	@ ${BOOKS}/srctangle ${IN}/Makefile.org warm.data >${INT}/algebra/warm.data

#+end_src
#+NAME: warm.data
#+begin_src common-lisp :noweb yes
(in-package "BOOT")
(setq |$topicHash| (make-hash-table))
(setf (gethash '|basic| |$topicHash|) 2)
(setf (gethash '|algebraic| |$topicHash|) 4)
(setf (gethash '|miscellaneous| |$topicHash|) 13)
(setf (gethash '|extraction| |$topicHash|) 6)
(setf (gethash '|conversion| |$topicHash|) 7)
(setf (gethash '|hidden| |$topicHash|) 3)
(setf (gethash '|extended| |$topicHash|) 1)
(setf (gethash '|destructive| |$topicHash|) 5)
(setf (gethash '|transformation| |$topicHash|) 10)
(setf (gethash '|hyperbolic| |$topicHash|) 12)
(setf (gethash '|construct| |$topicHash|) 9)
(setf (gethash '|predicate| |$topicHash|) 8)
(setf (gethash '|trignometric| |$topicHash|) 11)

#+end_src
** Building DEPSYS
The depsys image proceeds all else. it is the compile-time environment
for all interpreter code. 

The ``:oldboot'' symbol is pushed on the features list 
because there is a function
in util.lisp that emulates the new boot parser command BOOTTOCL. since
we eventually plan to move to the new boot parser this function (and
the push) should disappear.

The load of postpar and parse (without extensions) allows the 
=.${LISP}=
form to be loaded in a virgin system. However, if depsys is recreated then
the compiled form will get loaded.

This file contained the only mention of the AKCLDIR variable which
gives the path to the version of AKCL. Now that the system is running
on GCL this variable has been renamed to GCLDIR. This cannot be eliminated
entirely because the system uses this variable to look up a file 
called collectfn.lsp which is part of the GCL distribution. This
file lookup is in conditional lisp code so other lisps will not 
see the file load. The collectfn.lsp code is used by GCL to generate
the ``.fn'' files which are used to optimize function calling.

*** save depsys image
Once the appropriate commands are in the =${OUT}/makedep.lisp= file
we can load the file into a fresh image and save it. At least that's
how it used to work. In freebsd we cannot do this so we have to use
a much more complicated procedure.
This code used to read:
#+begin_example
\begin{chunk}{save depsys image}
	@ (cd ${MNT}/${SYS}/bin ; \
	   echo '(progn (load "${OUT}/makedep.lisp")' \
		'(spad-save "${DEPSYS}"))' | ${LISPSYS})
\end{chunk}
#+end_example

Now game is much more difficult. 
#+begin_example

 '(progn \

#+end_example

=si::*collect-binary-modules*= instructs GCL to build a list of 
binary object modules loaded into the current session with (load ...)
The list will be stored in =si::*binary-modules*=.
#+begin_example

	       (setq si::*collect-binary-modules* t) \
	       (load "${OUT}/makedep.lisp") \

#+end_example

=compiler::link= is a lisp interface to the ``ld'' C-based system linker.
The first argumet is a list of .o binary object modules to link into a
fresh gcl image. The second argument is the name of the new output
image.  The third argument is a string containing an initialization
command to run in the new image to reinitialize the heap.  The fourth
argument is a list of external C libraries, either static or dynamic,
that one wishes to link into the fresh image.  The last argument is a
flag which indicates whether GCL should initialize all of the freshly
linked in new lisp modules, or whether it should transparently
redirect load calls in the new image to initialization calls for the
already linked in module.

Some lisp systems, such as acl2, have a complex heap initialization,
in which load calls must be interspersed with other form evaluation
comprising the logic of the heap construction.  Others, such as
maxima, have no such complex initialization sequence.
#+begin_example
  (compiler::link \
#+end_example
=si::*binary-modules*= here has the list of compiled lisp binary module
.o files loaded by makedep.lsp above.
#+begin_example
   (remove-duplicates si::*binary-modules* \
		      :test (quote equal)) \
#+end_example

The name of the output image.
#+begin_example
   "$(DEPSYS)" \
#+end_example

This will be run in the newly linked sub-image.
#+begin_example
    (format nil "\
#+end_example

Collect loaded binary modules again to make sure that there are none,
as all should be already linked in via ld.  For error checking
purposes.
#+begin_example
     (setq si::*collect-binary-modules* t) \
#+end_example

We need to find =gcl_collectfn.lsp=, so set the *load-path*, and make
sure the source, not the binary, form is loaded here, as we're only
using this entire sequence on machines which cannot load binary object
modules and preserve them in saved images.
#+begin_example
     (let ((si::*load-path* (cons ~S si::*load-path*))\
	   (si::*load-types* ~S))\
#+end_example

Turn on function analyzation and autoload thereby =gcl_collectfn.lsp=.
#+begin_example
      (compiler::emit-fn t))\
#+end_example

Load the heap creation sequence again in the fresh new image, this
time transparently redirecting all calls to load of binary modules
invoked thereby into initialization calls for the already linkned in
module.

Load has code in it to recognize when a module is already linked in,
and to forgo in this case the actual load and replace with a mere
initialization call instead.
#+begin_example
      (load \"$(OUT)/makedep.lisp\")\
      (gbc t)\
#+end_example

It is an error to load a binary module. Calling load will not
reload them but only run initialization.
Throw an error if we've actually loaded any binary modules.
#+begin_example
     (when si::*binary-modules* \
       (error si::*binary-modules*))\
#+end_example

Unset the binary module collection flags.
#+begin_example
    (setq si::collect-binary-modules* nil \xo
	  si::*binary-modules* nil)\
    (gbc t)\
#+end_example

We need to forget the build time system paths per Camm Maguire's email
on July 14th, 2011
#+begin_example
     (si::reset-sys-paths)
#+end_example

Turn on SGC (Stratified Garbage Collection) in the final image.  This
is a optional gbc algorithm which is suitable for images which will
not grow much further.  It marks a large fraction of the heap
read-only, eliminating such pages from the time-consuming gbc
processing.  When writes are actually made to such pages, a segfault
is triggered which is handled by a function which remarks the pages
read-write and continues.
#+begin_example
   (when (fboundp (quote si::sgc-on)) (si::sgc-on t))\
#+end_example

This is a flag which instructs the GCL compiler to make unique
initialzation function C names.  This is necessary when using ld, as
all function names must be unique.
#+begin_example
   (setq compiler::*default-system-p* t)\
#+end_example
si::*system-directory* goes into the *load-path*, and .lsp in the *load-types*.
#+begin_example
 " si::*system-directory* (quote (list ".lsp")))\
#+end_example
No C libraries to link in here.
#+begin_example
   "" \
#+end_example

Do not run the initialization code for the newly linked in lisp
modules ``by hand'', but rather rely on the transparent load redirection
described above to initialize at the proper moment in the heap
initialization sequence.
#+begin_example
     nil))' | $(LISPSYS))
#+end_example

The save depsys image was supposed to read:
#+begin_example
 @ (cd ${OBJ}/${SYS}/bin ; \
   echo '(progn' \
    '(setq si::*collect-binary-modules* t)' \
    '(load "${OUT}/makedep.lisp")' \
    '(compiler::link' \
      '(remove-duplicates si::*binary-modules*' \
			':test (quote equal))' \
      '"$(DEPSYS)"' \
      '(format nil' \
	 '"(setq si::*collect-binary-modules* t)' \
	  '(let ((si::*load-path* (cons ~S si::*load-path*))' \
		  '(si::*load-types* ~S))' \
	  	  '(compiler::emit-fn t))' \
	  '(load \"$(OUT)/makedep.lisp\")' \
	  '(gbc t)' \
	  '(when si::*binary-modules*' \
		'(error si::*binary-modules*))' \
	  '(setq si::collect-binary-modules* nil' \
		'si::*binary-modules* nil)' \
	  '(gbc t)' \
	  '(si::reset-sys-paths)' \
	  '(when (fboundp (quote si::sgc-on)) (si::sgc-on t))' \
	  '(setq compiler::*default-system-p* t)"' \
	 'si::*system-directory* (quote (list ".lsp")))'\
       '""' \
       'nil))' | $(LISPSYS))
#+end_example

This scheme does not work. It fails during loading with multiple messages
of the form:
#+begin_example
/home/axiom33/obj/linux/interp/parse.o(.text+0x5660): 
 In function `init_code':
  : multiple definition of `init_code'
/home/axiom33/obj/linux/interp/postpar.o(.text+0x4e78): 
  first defined here
#+end_example
#+NAME: depsys
#+begin_src common-lisp :noweb yes
${DEPSYS}:	${DEP} ${OUT}/sys-pkg.${LISP} ${OUT}/nocompil.${LISP} \
		${OUT}/bookvol5.${LISP} ${OUT}/bookvol9.${LISP} \
		${OUT}/util.${LISP} \
		${OUT}/parsing.${LISP} \
		${OUT}/g-boot.lisp ${OUT}/c-util.lisp \
		${OUT}/g-util.lisp \
		${OUT}/clam.lisp \
		${OUT}/slam.lisp ${LOADSYS}
	@ echo si002 making ${DEPSYS} 
	@ echo '${PROCLAIMS}' > ${OUT}/makedep.lisp
	@ echo '(push :oldboot *features*)' >>${OUT}/makedep.lisp
# depsys deliberately loads SOURCE (the compile environment must not
# depend on fasls it is about to produce). The extension is explicit
# because an extensionless load beside a stale fasl from the interpsys
# leg makes SBCL refuse with "object file is older than the presumed
# source" (observed); naming the .${LISP} pins the choice on any host.
	@ echo '(load "${OUT}/nocompil.${LISP}")' >> ${OUT}/makedep.lisp
	@ echo '(load "${OUT}/bookvol5.${LISP}")' >> ${OUT}/makedep.lisp
	@ echo '(load "${OUT}/bookvol9.${LISP}")' >> ${OUT}/makedep.lisp
	@ echo '(load "${OUT}/util.${LISP}")' >> ${OUT}/makedep.lisp
	@ echo '(in-package "BOOT")' >> ${OUT}/makedep.lisp
	@ echo '(build-depsys (quote ($(patsubst %, "%", ${DEP})))' \
	  '"${SPAD}" "${GCLDIR}" "${SRC}" "${INT}" "${OBJ}" "${MNT}"' \
	  '"${SYS}")' >> ${OUT}/makedep.lisp
	@ echo '(unless (probe-file "${OUT}/parsing.${O}")' \
	  '(compile-file "${OUT}/parsing.${LISP}"' \
	  ':output-file "${OUT}/parsing.${O}"))' >> ${OUT}/makedep.lisp
	@ echo '(load "${OUT}/parsing")' >> ${OUT}/makedep.lisp
	@ echo '(unless (probe-file "${OUT}/clam.${O}")' \
	  '(compile-file "${OUT}/clam.lisp"' \
	  ':output-file "${OUT}/clam.${O}"))' >> ${OUT}/makedep.lisp
	@ echo '(load "${OUT}/clam")' >> ${OUT}/makedep.lisp
	@ echo '(unless (probe-file "${OUT}/slam.${O}")' \
	  '(compile-file "${OUT}/slam.lisp"' \
	  ':output-file "${OUT}/slam.${O}"))' >> ${OUT}/makedep.lisp
	@ echo '(load "${OUT}/slam")' >> ${OUT}/makedep.lisp
	@ echo '(unless (probe-file "${OUT}/g-boot.${O}")' \
	  '(compile-file "${OUT}/g-boot.lisp"' \
	  ':output-file "${OUT}/g-boot.${O}"))' >> ${OUT}/makedep.lisp
	@ echo '(load "${OUT}/g-boot")' >> ${OUT}/makedep.lisp
	@ echo '(unless (probe-file "${OUT}/c-util.${O}")' \
	  '(compile-file "${OUT}/c-util.lisp"' \
	  ':output-file "${OUT}/c-util.${O}"))' >> ${OUT}/makedep.lisp
	@ echo '(load "${OUT}/c-util")' >> ${OUT}/makedep.lisp
	@ echo '(unless (probe-file "${OUT}/g-util.${O}")' \
	  '(compile-file "${OUT}/g-util.lisp"' \
	  ':output-file "${OUT}/g-util.${O}"))' >> ${OUT}/makedep.lisp

	@ echo '(load "${OUT}/g-util")' >> ${OUT}/makedep.lisp
<<save depsys image>>
	@ echo si003 ${DEPSYS} created

#+end_src
** Building SAVESYS and AXIOMSYS
GCL likes to tell you when it has replaced a function call by a 
tail-recursive call. This happens when the last form in a function
is a call to the same function. In general, we don't care so we set
compiler::*suppress-compiler-notes* to true in order to reduce the noise.
#+NAME: savesys
#+begin_src common-lisp :noweb yes
${SAVESYS}:	${DEPSYS} ${OBJS} ${OUT}/bookvol5.${O} ${OUT}/util.${O} \
		${OUT}/nocompil.${LISP} ${OUT}/sys-pkg.${LISP} \
		${OUTINTERP} ${BROBJS} \
		${OUT}/database.date ${INOBJS} ${ASCOMP} \
		${NAGBROBJS} \
		${LOADSYS} \
		${SRC}/doc/msgs/s2-us.msgs \
		${INT}/algebra/warm.data
	@ echo si004 invoking make in `pwd` with parms:
	@ echo SYS= ${SYS} 
	@ echo LSP= ${LSP} 
	@ echo PART= ${PART} 
	@ echo SPAD= ${SPAD} 
	@ echo SRC= ${SRC} 
	@ echo INT= ${INT}
	@ echo MID= ${MID} 
	@ echo OUT= ${OUT}
	@ echo OBJ= ${OBJ} 
	@ echo MNT= ${MNT} 
	@ echo O=${O} LISP=${LISP} BYE=${BYE}
# The .fn files are GCL gcl_collectfn's type-information output, emitted
# during compile-file to drive call optimization. SBCL produces none,
# so the copy has nothing to stat and is skipped on that host.
ifneq (${LISPFLAVOR},sbcl)
	@ cp -p ${OUT}/*.fn ${MID}
endif
	@ cp -p ${SRC}/doc/msgs/s2-us.msgs ${SPAD}/doc/msgs
	@ echo '${PROCLAIMS}' > ${OUT}/makeint.lisp
	@ echo '(load "${OUT}/nocompil")' >> ${OUT}/makeint.lisp
	@ echo '(load "${OUT}/bookvol5")' >> ${OUT}/makeint.lisp
	@ echo '(load "${OUT}/util")' >> ${OUT}/makeint.lisp
	@ echo '(in-package "BOOT")' >> ${OUT}/makeint.lisp
	@ touch ${TIMESTAMP}
	@ echo '${YEARWEEK}' >> ${OUT}/makeint.lisp
	@ echo '(build-interpsys (append' \
	  '(quote ($(patsubst %, "%", ${OBJS})))'  \
	  '(quote ($(patsubst %, "%", ${ASCOMP})))'  \
	  '(quote ($(patsubst %, "%", ${INOBJS}))))' \
	  '(quote ($(patsubst %, "%", ${BROBJS})))'  \
	  '(quote ($(patsubst %, "%", ${NAGBROBJS})))'  \
	  '"${SPAD}"  "${LSP}" "${SRC}" "${INT}"' \
	  '"${OBJ}" "${MNT}" "${SYS}")' >> ${OUT}/makeint.lisp
# The package sys-pkg creates is SCRATCHPAD_COMPILER (underscore); the
# hyphenated name here never existed anywhere -- CLtL1's in-package
# silently CREATED it as an empty package on GCL, where ANSI's signals
# package-does-not-exist (observed, right after build-interpsys
# finished). The underscore package gives the identical effect -- an
# empty package context for the set-restart-hook call that follows --
# and exists on both hosts.
	@ echo '(in-package "SCRATCHPAD_COMPILER")' >> ${OUT}/makeint.lisp
	@ echo '(boot::set-restart-hook)' >> ${OUT}/makeint.lisp
	@ echo '(in-package "BOOT")' >> ${OUT}/makeint.lisp
	@ echo '(load "${INT}/algebra/warm.data")' >> ${OUT}/makeint.lisp
	@ echo '(|clearClams|)' >> ${OUT}/makeint.lisp
	@ echo '#+:akcl (setq compiler::*suppress-compiler-notes* t)' \
		>> ${OUT}/makeint.lisp
	@ echo '#+:akcl (si::gbc-time 0)' >> ${OUT}/makeint.lisp
	@ echo '#+:akcl (setq si::*system-directory* "${SPAD}/bin/")' \
	       >> ${OUT}/makeint.lisp
# The save wrapper is piped into a FRESH bin/lisp, which on SBCL has
# none of the build's packages yet. The GCL form wraps the load in
# (gbc t) collections and names user::spad-save -- but gbc is
# undefined before makeint loads it, and user:: cannot even be READ
# until makeint's first form installs the USER nickname (the whole
# progn is read before any of it evaluates). The SBCL form drops the
# gbc calls (it collects on its own) and names spad-save unqualified:
# read in COMMON-LISP-USER, it interns there, and makeint's load of
# bookvol5 defines user::spad-save -- the same symbol via the nickname.
ifeq (${LISPFLAVOR},sbcl)
	@ (cd ${OBJ}/${SYS}/bin ; \
	  echo '(progn (load "${OUT}/makeint.lisp")' \
		 '(spad-save "${SAVESYS}"))' | ${LISPSYS} )
else
	@ (cd ${OBJ}/${SYS}/bin ; \
	  echo '(progn (gbc t) (load "${OUT}/makeint.lisp")' \
		 '(gbc t) (user::spad-save "${SAVESYS}"))' | ${LISPSYS} )
endif
	@ echo si005 ${SAVESYS} created
	@ cp ${SAVESYS} ${AXIOMSYS}
	@ echo si006 ${AXIOMSYS} created

#+end_src

** Building debugsys
Note that we assume you've already built interpsys so all of the
files are known to exist and be up to date. We don't list any of
the preconditions here. 
#+NAME: debugsys
#+begin_src common-lisp :noweb yes
${DEBUGSYS}: ${MID}/debugsys.lisp
	@ echo si007 building debugsys
	@ (cd ${OBJ}/${SYS}/bin ; \
	  echo '(progn (gbc t) (load "${MID}/debugsys.lisp")' \
		 '(user::spad-save "${DEBUGSYS}"))' | ${LISPSYS} )
	@ echo si008 ${DEBUGSYS} created

#+end_src

** The Interpreter files

\subsection{debugsys.lisp [cite:@14]}
The *debugsys.lisp* file is used to create a *debugsys* runnable image.
This image contains almost all of the lisp code that make up the axiom
interpreter in lisp form. It is useful for deep system debugging but
otherwise worthless. This file is certain to drift over time as changes
are made elsewhere to add or remove files. It is assumed that you know
what you are doing if you change this file or use debugsys.

This file is basically the same as the one created during the build of
interpsys. See the echo lines in the *SAVESYS* block above. These
are echoed into a temporary file which gets loaded into the lisp image.
We simply captured that temporary file, replaced the .o files with .lisp
files (or .lsp or .clisp) and saved it here.
#+NAME: debugsys.lisp (MID from IN)
#+begin_src common-lisp :noweb yes
${MID}/debugsys.lisp: ${IN}/debugsys.lisp.org
	@ echo si011 making ${MID}/debugsys.lisp from ${IN}/debugsys.lisp.org
	@ (cd ${MID} ; \
	  ${BOOKS}/srctangle ${IN}/debugsys.lisp.org "*" > debugsys.lisp 2>/dev/null)

#+end_src

** The databases
*** autoload dependencies
If you are adding a file which is to be autoloaded the following step
information is useful. There are 2 cases:
\begin{enumerate}
\item adding files to currently autoloaded parts\\
(as of 2/92: browser old parser and old compiler)
\item adding new files
\begin{itemize}
\item case 1:
\item [(a)] you have to add the file to the list of files currently there
(e.g. see BROBJS above)
\item [(b)] add an autolaod rule
(e.g. ${AUTO}/parsing.${O}: ${OUT}/parsing.${O})
\item [(c)] edit util.lisp to add the 'external' function (those that
should trigger the autoload
\end{itemize}
\item case 2:\\
     build-interpsys (in util.lisp) needs an extra argument for the
     new autoload things and several functions in util.lisp need hacking.
\end{enumerate}
database.date is a marker file used to force a rebuild of interpsys if the
database is rebuilt (src/algebra/Makefile).
#+NAME: databases
#+begin_src common-lisp :noweb yes
${OUT}/database.date:
	@ echo 617 the database was updated...remaking interpsys
	@ touch ${OUT}/database.date

#+end_src

** The Makefile
#+NAME: *
#+begin_src common-lisp :noweb yes

<<environment>>

all: announce ${SAVESYS} # ${DEBUGSYS} 
	@echo 618 finished ${IN}

announce:
	@ echo =====================================
	@ echo src/interp BUILDING INTERPRETER FILES
	@ echo =====================================

clean:
	@echo 619 cleaning ${SRC}/interp

<<savesys>>
<<depsys>>
<<debugsys>>
<<databases>>

<<debugsys.lisp (MID from IN)>>

<<warm.data.stanza>>

${MID}/bookvol5.${LISP}: ${IN}/bookvol5.org
	@ echo si125 making ${MID}/bookvol5.${LISP} from ${IN}/bookvol5.org
	@ (cd ${MID} ; \
  ${BOOKS}/srctangle ${IN}/bookvol5.org "Interpreter" > bookvol5.${LISP} )  1>/dev/null 2>/dev/null

${MID}/bookvol9.${LISP}: ${IN}/bookvol9.org
	@ echo si128 making ${MID}/bookvol9.${LISP} from ${IN}/bookvol9.org
	@ (cd ${MID} ; \
     ${BOOKS}/srctangle ${IN}/bookvol9.org "Compiler" > bookvol9.${LISP} ) 1>/dev/null 2>/dev/null

${MID}/bookvol10.5.${LISP}: ${IN}/bookvol10.5.org
	@ echo si131 making ${MID}/bookvol10.5.${LISP} from ${IN}/bookvol10.5.org
	@ (cd ${MID} ; \
	${BOOKS}/srctangle ${IN}/bookvol10.5.org "Numerics" > bookvol10.5.${LISP} ) 1>/dev/null 2>/dev/null

${MID}/http.lisp: ${IN}/http.lisp
	@ echo si110 making ${MID}/http.lisp from ${IN}/http.lisp
	@( cp ${IN}/http.lisp ${MID}/http.lisp )

${OUT}/%.${LISP}: ${MID}/%.${LISP}
	@ echo siOUTfromMID2 making ${OUT}/$*.${LISP} from ${MID}/$*.${LISP}
	@cp ${MID}/$*.${LISP} ${OUT}/$*.${LISP}

${OUT}/%.${LISP}: ${MID}/%.lisp
	@ echo siOUTfromMID1 making ${OUT}/$*.lisp from ${MID}/$*.lisp
	@cp ${MID}/$*.lisp ${OUT}/$*.${LISP}

${OUT}/%.lisp: ${IN}/%.lisp.org
	@ echo siOUTfromIN making ${OUT}/$*.lisp from ${IN}/$*.lisp.org
	@ rm -f ${OUT}/$*.${O}
	@( cd ${OUT} ; \
	  ${BOOKS}/srctangle ${IN}/$*.lisp.org "*" > $*.lisp ) 1>/dev/null

# The compiled-object extension follows the host (${O}: o on GCL,
# fasl on SBCL), so the pattern target and both output-file forms use
# ${O} instead of a hardcoded .o -- otherwise an SBCL build has no
# rule for the vmlisp.fasl that interpsys depends on (observed).
# The quiet branch's output-file used to say $I.o: $I is an undefined
# make variable, so the file landed at "${OUT}/.o" -- visible in old
# GCL build trees as a literal ".o" file. It now matches the stem.
${OUT}/%.${O}: ${MID}/%.lisp
	@ echo siOUTfromMID making ${OUT}/$*.${O} from ${MID}/$*.lisp
	@ if [ -z "${NOISE}" ] ; then \
	   (cd ${MID} ; \
	    echo '(progn  (compile-file "$*.lisp"' \
	     ':output-file "${OUT}/$*.${O}") (${BYE}))' | ${DEPSYS} ) ; \
	   else \
	    (cd ${MID} ; \
	     echo '(progn  (compile-file "$*.lisp"' \
	     ':output-file "${OUT}/$*.${O}") (${BYE}))' | ${DEPSYS} ) \
	      1>/dev/null 2>/dev/null ; \
	   fi

${MID}/%.lisp: ${IN}/%.lisp.org
	@ echo siMIDfromIN making ${MID}/$*.lisp from ${IN}/$*.lisp.org
	@ (cd ${MID} ; \
	  ( ${BOOKS}/srctangle ${IN}/$*.lisp.org "*" > $*.lisp 2>/dev/null ) )

${AUTO}/%.${O}: ${OUT}/%.${O}
	@ echo siAUTOfromOUT making ${AUTO}/$*.${O} from ${OUT}/$*.${O}
	@ cp ${OUT}/$*.${O} ${AUTO}

${OUT}/%.${O}: ${MID}/%.${LISP}
	@ echo si123 making ${OUT}/$*.${O} from ${MID}/$*.${LISP}
	@  if [ -z "${NOISE}" ] ; then \
	 (cd ${MID} ; \
	   echo '(progn  (compile-file "${MID}/$*.${LISP}"' \
	     ':output-file "${OUT}/$*.${O}") (${BYE}))' | ${DEPSYS} ) ; \
	  else \
	  (cd ${MID} ; \
	   echo '(progn  (compile-file "${MID}/$*.${LISP}"' \
	     ':output-file "${OUT}/$*.${O}") (${BYE}))' | ${DEPSYS} ) \
	      1>/dev/null 2>/dev/null ; \
	  fi 

#+end_src
\begin{thebibliography}{99}
\end{thebibliography}
\end{document}
