#+LATEX: \documentclass{article}
#+LATEX: \usepackage{axiom}
#+LATEX: \begin{document}
#+TITLE: The Top Level Makefile
#+AUTHOR: Timothy Daly
#+BEGIN_abstract
#+END_abstract
** The overall build process

Makefiles are responsible for building all of their subdirectories
and then themselves. The system is built in the following order
1. books       -- building pdf files
2. src/scripts -- building scripts
3. src/lib     -- building lib files
4. lsp       -- building gcl common lisp
5. src       -- building src
6. src/interp  -- building interpreter files
7. src/share   -- building share files
8. src/algebra -- building help files
9. src/algebra -- building input files
10. src/algebra -- building xhtml files
11. src/algebra -- building algebra files
  - algebra bootstrap complete
  - layer 0 of 24 complete
  - layer 1 of 24 complete
  - layer 2 of 24 complete
  - layer 3 of 24 complete
  - layer 4 of 24 complete
  - layer 5 of 24 complete
  - layer 6 of 24 complete
  - layer 7 of 24 complete
  - layer 8 of 24 complete
  - layer 9 of 24 complete
  - layer 10 of 24 complete
  - layer 11 of 24 complete
  - layer 12 of 24 complete
  - layer 13 of 24 complete
  - layer 14 of 24 complete
  - layer 15 of 24 complete
  - layer 16 of 24 complete
  - layer 17 of 24 complete
  - layer 18 of 24 complete
  - layer 19 of 24 complete
  - layer 20 of 24 complete
  - layer 21 of 24 complete
  - layer 22 of 24 complete
  - layer 23 of 24 complete
  - layer 0 copy complete
12. src/etc   -- building etc
13. src/doc   -- building doc files
14. src/input -- running regression tests


** General Makefile Structure

Makefiles are responsible for four things. First, they have to set up
the output directory structure so that all of the build machinery
can assume it exists. Second, they have to build all of the files
in their own directory. Third, they have to invoke Make on each
of their subdirectories. This forms a natural tree walk of the
directory structure. Fourth, they have to explain all of the details
about the directory, the files it manages and its subdirectories.

The clean stanza has been modified to be more effective. Previously
it walked the Makefile hierarchy trying to clean subdirectories. This
method often fails for various reasons (e.g. permissions, incomplete
builds, etc). Now we simply remove the created files directly.

*** The Top Level Makefile
We have added a stanza to separate the build of documents from the build
of source files. As much as possible we would like to do the document
builds in parallel with the source builds. We kick off a make for the
documents in the background and then kick off a make in the foreground
for the source code. This is independent of using make in parallel and
instead uses the shell to fork the processes. We have not had much luck
getting make to build in parallel reliably.

Note that make cannot handle recursively calling itself in the same
directory so we have to expand the serial forms inline. Cheesy.

#+NAME: parallel
#+begin_src common-lisp :noweb yes
all: srctangle-tools rootdirs axiom.sty tanglec libspad lspdir
	@ echo 1 making a ${SYS} system, PART=${PART} SUBPART=${SUBPART}
	@ echo 2 Environment ${ENV}
	@ ${BOOKS}/srctangle Makefile.org "Makefile.${SYS}" >Makefile.${SYS}
	@ cp ${BOOKS}/dvipdfm.def ${MNT}/${SYS}/doc
	@ cp ${BOOKS}/changepage.sty ${MNT}/${SYS}/doc
	@ ${EXTRACT} Makefile.org
	@ cp Makefile.pdf ${MNT}/${SYS}/doc/src/root.Makefile.pdf
	@ if [ "${RUNTYPE}" = "parallel" ] ; then \
	   ( echo p4 starting parallel make of input files ; \
	     ${ENV} ${MAKE} input ${NOISE} & ) ; \
	  else \
	   if [ "${BUILD}" = "full" ] ; then \
	   ( echo s4 starting serial make of input files ; \
	     cd ${MNT}/${SYS}/doc/src/input ; \
	     cp ${BOOKS}/axiom.sty . ; \
	     cp ${SRC}/input/*.eps . ; \
	     for i in `ls ${SRC}/input/*.input.org` ; do \
	      if [ .${NOISE} = . ] ; \
	      then \
	       latex $$i ; \
	      else \
	       ( echo p4a making $$i ; \
		 latex $$i >${TMP}/trace ) ; \
	      fi ; \
	     done ; \
	     rm -f *~ ; \
	     rm -f *.pamphlet~ ; \
	     rm -f *.log ; \
	     rm -f *.tex ; \
	     rm -f *.toc ; \
	     rm -f *.aux ) ; fi ; \
	  fi
	@ if [ "${RUNTYPE}" = "parallel" ] ; then \
	    ( echo s2 starting parallel make of books ; \
	      echo s3 ${SPD}/books/Makefile from \
		   ${SPD}/books/Makefile.org ; \
	      cd ${SPD}/books ; \
	      ${EXTRACT} Makefile.org ; \
	      cp Makefile.pdf ${MNT}/${SYS}/doc/src/books.Makefile.pdf ; \
	      ${ENV} ${MAKE} & ) ; \
	  else \
	    ( echo s2 starting serial make of books ; \
	      echo s3 ${SPD}/books/Makefile from \
		   ${SPD}/books/Makefile.org ; \
	      cd ${SPD}/books ; \
	      ${EXTRACT} Makefile.org ; \
	      cp Makefile.pdf ${MNT}/${SYS}/doc/src/books.Makefile.pdf ; \
	      if [ "${BUILD}" = "full" ] ; then \
	      ${ENV} ${MAKE} ; fi ) ; \
	  fi
	@ echo p7 starting make of src
	@ ${ENV} $(MAKE) -f Makefile.${SYS} 
	@ echo 3 finished system build on `date` | tee >lastBuildDate

<<lsp>>

libspad: 
	@ echo 11a making libspad
	@ ( cd ${OBJ}/${SYS}/lib ; \
	    ${BOOKS}/srctangle ${BOOKS}/bookvol8.org Makefile >Makefile ; \
	    ${ENV} ${MAKE} libspad.a )

axiom.sty:
	@ echo 11c copying books/axiom.sty
	@ cp ${BOOKS}/axiom.sty .

rootdirs:
	@ echo 11 checking directory structure
	 mkdir -p ${TMP}
	 mkdir -p ${INT}/algebra
	 mkdir -p ${INT}/hyper
	 mkdir -p ${INT}/input
	 mkdir -p ${INT}/interp
	 mkdir -p ${INT}/sman
	 mkdir -p ${OBJ}/${SYS}/bin
	 mkdir -p ${OBJ}/${SYS}/etc
	 mkdir -p ${OBJ}/${SYS}/graph
	 mkdir -p ${OBJ}/${SYS}/hyper/pages
	 mkdir -p ${OBJ}/${SYS}/interp
	 mkdir -p ${OBJ}/${SYS}/lib
	 mkdir -p ${OBJ}/${SYS}/sman
	 mkdir -p ${OBJ}/${SYS}/proofs
	 mkdir -p ${MNT}/doc
	 mkdir -p ${MNT}/${SYS}/algebra
	 mkdir -p ${MNT}/${SYS}/src/algebra
	 mkdir -p ${MNT}/${SYS}/autoload
	 mkdir -p ${MNT}/${SYS}/bin
	 mkdir -p ${MNT}/${SYS}/doc/axbook
	 mkdir -p ${MNT}/${SYS}/doc/bitmaps
	 mkdir -p ${MNT}/${SYS}/doc/hypertex/bitmaps
	 mkdir -p ${MNT}/${SYS}/doc/msgs
	 mkdir -p ${MNT}/${SYS}/doc/ps
	 mkdir -p ${MNT}/${SYS}/doc/cookbook
	 mkdir -p ${MNT}/${SYS}/doc/spadhelp
	 mkdir -p ${MNT}/${SYS}/doc/src/input
	 mkdir -p ${MNT}/${SYS}/graph/parabola.view
	 mkdir -p ${MNT}/${SYS}/input
	 mkdir -p ${MNT}/${SYS}/lib/graph
	 mkdir -p ${MNT}/${SYS}/lib/scripts

input:
	@ echo p9 making input documents
	@ if [ "${BUILD}" = "full" ] ; then \
	  ( cd ${MNT}/${SYS}/doc/src/input ; \
	    cp ${BOOKS}/axiom.sty . ; \
	    for i in `ls ${SRC}/input/*.input.org` ; \
	      do latex $$i ; \
	      done ; \
	     rm -f *~ ; \
	     rm -f *.pamphlet~ ; \
	     rm -f *.log ; \
	     rm -f *.tex ; \
	     rm -f *.toc ; \
	     rm -f *.aux ) ; fi

#+end_src

#+NAME: *
#+begin_src common-lisp :noweb yes
<<ENVDEFAULTS>>
<<ENVAR>>
<<parallel>>
<<book>>
<<tanglec.c>>
<<literate commands>>
<<install>>

document: 
	@ echo 4 making a ${SYS} system, PART=${PART} SUBPART=${SUBPART}
	@ echo 5 Environment ${ENV}
	@ ${BOOKS}/srctangle Makefile.org "Makefile.${SYS}" >Makefile.${SYS}
	@ ${ENV} $(MAKE) -f Makefile.${SYS} document
	@echo 6 finished system build on `date` | tee >lastBuildDate

clean: 
	@ echo 7 making a ${SYS} system, PART=${PART} SUBPART=${SUBPART}
	@ echo 8 Environment ${ENV}
	@ rm -f axiom.sty
	@ rm -f Makefile.pdf
	@ rm -f Makefile.dvi
	@ rm -f Makefile.${SYS}
	@ rm -f books/Makefile
	@ rm -f books/Makefile.dvi
	@ rm -f books/Makefile.pdf
	@ rm -f books/axiom.bib
	@ rm -f books/sortsig.lisp
	@ rm -f lsp/axiom.sty
	@ rm -f lsp/Makefile lsp/Makefile.dvi lsp/Makefile.pdf
	@ rm -rf lsp/gcl*
	@ rm -f src/axiom.sty
	@ rm -f src/Makefile
	@ rm -f src/Makefile.dvi
	@ rm -f src/Makefile.pdf
	@ rm -f src/algebra/book*pamphlet
	@ rm -f src/algebra/*.spad
	@ rm -f src/algebra/Makefile
	@ rm -f src/etc/axiom.sty
	@ rm -f src/etc/Makefile src/etc/Makefile.dvi src/etc/Makefile.pdf
	@ rm -f src/interp/book*pamphlet
	@ rm -f src/interp/axiom.sty
	@ rm -f src/input/axiom.sty
	@ rm -f src/share/axiom.sty
	@ rm -f src/share/Makefile src/share/Makefile.dvi 
	@ rm -f src/share/Makefile.pdf
	@ rm -rf int
	@ rm -rf obj
	@ rm -rf mnt
	@ for i in `find . -name "*~"` ; do rm -f $$i ; done
	@ rm -f lastBuildDate
	@ rm -f books/tanglec
	@ rm -f src/input/Makefile src/input/Makefile.dvi
	@ rm -f src/input/Makefile.pdf 
	@ rm -f src/interp/Makefile src/interp/Makefile.dvi
	@ rm -f src/interp/Makefile.pdf 
	@ rm -f src/share/Makefile src/share/Makefile.dvi
	@ rm -f src/share/Makefile.pdf 
	@ rm -f Makefile.aux
	@ rm -f Makefile.log

#+end_src

*** Environment

**** VERSION
The VERSION variable is a unique string intended to show up
in the banner at startup time. I can be anything but is intended
to be a unique way of identifying the CVS version so we can 
reference bug reports to versions.

The VERSION variable is used in the src/interp/Makefile
to set a lisp variable boot::*build-version*. This variable
is used by the =yearweek= function to construct the banner.

The banner also contains a build timestamp so we can determine
when the image is compiled. We touch the file 
called =${MNT}/${SYS}/timestamp= and using a formatted form
of its file information. See the YEARWEEK variable in the
src/interp/Makefile.pamphlet and the =yearweek= function in 
src/interp/util.lisp.pamphlet.

**** SPAD
The SPAD environment variable is normally specified.
It is expected to be a path to the top level directory of the
shipped system. For example, if we want to build a linux system
the SPAD variable should look like:
\begin{verbatim}
    `pwd`/new/mnt/*linux*
\end{verbatim}
**** SYS
From the SPAD variable we look at the last directory name
and create a version of Axiom for that system. The SYS
environment variable is the last directory name in the SPAD
variable.

**** SPD
The SPD variable is taken to be the current working directory
where this Makefile lives. This is obviously the root of the whole
system source tree. All Makefiles form environment variables based
on this value.

Next we see the six top-level directories discussed above being
defined using the SPD variable. 

**** LSP
This variable specifies where the LSP subdirectory lives.
It is normally a directory at the top level of the system but
we do not assume that to be true. Other lisps might require it
to be elsewhere. 

**** GCLDIR
This file contained the only mention of the AKCLDIR variable which
gives the path to the version of AKCL. Now that the system is running
on GCL this variable has been renamed to GCLDIR. This cannot be eliminated
entirely because the system uses this variable to look up a file 
called collectfn.lsp which is part of the GCL distribution. This
file lookup is in conditional lisp code so other lisps will not 
see the file load. The collectfn.lsp code is used by GCL to generate
the ``.fn'' files which are used to optimize function calling.

Also, lsp/sys-proclaims.lisp is a file generated 
during the GCL build which contains type information about lisp
functions, allowing fast-function calling behavior. 

When defining the environment, the SPD variable is defined as the
current directory. SYS is taken as the last non-directory part of
the environment variable =$AXIOM= (e.g. if 
=$AXIOM=/(a-path)/mnt/linux=
then SYS=linux). It is *mandatory* that =$AXIOM= does
*not* contain any trailing slash, because the =notdir= function
will return the string following the final slash and would thus return
the empty string.

**** SRC
The SRC subdirectory is a hand-generated, read-only top level 
directory containing the source code. This is assumed to be completely
system-independent and, in general, it can reside on a CD or NFS
mounted file system. This is useful for building several different
kinds of systems (as specified by the SYS variable from a single
source tree.

**** INT

The INT subdirectory is a machine-generated, system-independent
top-level directory containing source code. Axiom builds from literate
sources.  This work only needs to be done once at the first build. The
INT directory is a cache of work. It can be erased at will. 
However steps such as generating lisp code from spad code, while
done by machine, are system-independent. Therefore this subdirectory,
once built, can reside with the SRC subdirectory on CD or NFS as a
read-only branch.

**** OBJ
The OBJ subdirectory is a machine-generated, system-dependent
top level directory containing things like compiler binaries. The
OBJ directory is a cache of work. It can be erased at will. 
Because it is system-dependent it needs to be written at build
time by compilers for each specific system. 

**** MNT
The MNT subdirectory is a complete, working copy of Axiom.
This directory contains everything that is needed to run Axiom and
can be copied anywhere. Everything in this directory takes its required
information from the =$AXIOM= shell variable. Once this directory is
copied the SRC, INT, and OBJ subdirectories can be erased.

**** ZIPS
The ZIPS subdirectory contains particular versions of subsystems
that Axiom needs in tar-gzip format. The Makefiles will unpack them.
It also contains patch files to these subsystems. The Makefile will
apply those patches. Then it will configure and build the required
subsystems.

**** TMP
The TMP directory is used in place of normal unix tmp in order to
avoid writing outside of our build tree.

Note that TMP is a workspace in the OBJ directory. It is
working space for temporary files since we cannot assume that
we can write outside our own tree. Output from commands like
the =document= command will generally be written to the
TMP/trace file. If the build seems to hang while making a
document file then check this file. It will contain the output
of the latex command and the likely error in the tex file.

**** SPADBIN
The SPADBIN directory is the path to the executable 
binary directory of the shipped system. The directory contains
all of the executable commands, such as the =document=
command. The =document= command lives in the SRC/SCRIPTS
subdirectory and will be copied to SPADBIN before we start
walking the build subtree.

**** INC
The INC directory contains all the include files for the C
programs.

**** The NOISE variable 
The NOISE variable is used in the calls to the document
command. In general, where the document command is called in
the Makefiles it is called with the following form:
\begin{verbatim}
   ${SPADBIN}/document ${NOISE} foo
\end{verbatim}
with the default value of NOISE being:
\begin{verbatim}
   NOISE="-o ${TMP}/trace"
\end{verbatim}

The reason NOISE exists is that the latex command will
generate a page of output which is uninteresting during the
make. However if there is a latex syntax error in a pamphlet
file the make will continue past the error due to the nonstopmode
flag. To see the actual error message rerun the make as:
\begin{verbatim}
  make NOISE=
\end{verbatim}

**** PART and SUBPART
Because of the size of this build we do everything possible to
minimize the work necessary to rebuild. In order to allow
finer control of the build we have two options that can be
specified. The first is the PART variable. The second
is the SUBPART variable. The PART variable basically
specifies which directory we wish to build.

Setting the PART as:
\begin{verbatim}
PART=foo
\end{verbatim}
will look for a stanza in the Makefile as:
\begin{verbatim}
\${PART}dir 
\end{verbatim}
which expands to:
\begin{verbatim}
foodir
\end{verbatim}

Variable PART can be specified (environment or command-line) as
one of:

\begin{verbatim}
 (all | lib | install | lisp | interp | comp | graph | hyper 
      | input | sman | boot | include | doc | algebra )
\end{verbatim}

It is possible to be more specific with a directory using SUBPART.


**** DESTDIR and COMMAND
The install directory is /usr/local/axiom by default 
but this can be changed on the command line by typing:
\begin{verbatim}
make DESTDIR=/yourabsolutepath COMMAND=fullPathAndCommand install
\end{verbatim}

The COMMAND string has been modified to use the DESTDIR
variable so we can properly find the axiom command.

The DOCUMENT variable is now set to replace the direct call
to the document command. This will allow it to be
changed on the command line.
** The Environment
#+NAME: ENVDEFAULTS
#+begin_src common-lisp :noweb yes
VERSION:="Axiom (May 2017)"

##### special paths
SPD:=$(shell pwd)
SRC:=${SPD}/src
LSP:=${SPD}/lsp
INT:=${SPD}/int
OBJ:=${SPD}/obj
MNT:=${SPD}/mnt
TMP:=${OBJ}/tmp
ZIPS:=${SPD}/zips
BOOKS:=${SPD}/books
SRCDIRS:="interpdir sharedir algebradir etcdir docdir \
	  graphdir smandir hyperdir browserdir inputdir"

SYS:=$(notdir $(AXIOM))
DAASE:=${SRC}/share
PROOFS:=${OBJ}/${SYS}/proofs
SPAD:=${SPD}/mnt/${SYS}

SPADBIN:=${MNT}/${SYS}/bin
DOCUMENT:=${SPADBIN}/document
EXTRACT:=${BOOKS}/extract

##### installation paths
DESTDIR:=/usr/local/axiom
COMMAND:=${DESTDIR}/mnt/${SYS}/bin/axiom

##### functions we need
AWK:=gawk 
PATCH:=patch
RANLIB:=ranlib
TAR:=tar
TOUCH:=touch
UNCOMPRESS:=gunzip

####K C Related variables
PLF=${SYS}platform
CCF="-O2 -fno-strength-reduce -D_GNU_SOURCE -D${PLF} \
     -I/usr/X11/include \
     -Wno-absolute-value -std=gnu89 -w" 
INC:=${SPD}/src/include
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF="-L/usr/X11/lib -L/usr/X11R6/lib64 -L/usr/local/lib64 -L/usr/openwin/lib64 -L/usr/lib64 "
O:=o

##### lisp related variables
BYE:=bye
<<GCLVERSION>>
GCLDIR:=${LSP}/${GCLVERSION}
<<GCLOPTS-LOCBFD>>
LISP:=lsp
<<LISPFLAVOR>>

##### command line control
NOISE:="-o ${TMP}/trace"
PART:=  cprogs
SUBPART:= everything
RUNTYPE:=serial
# can be richtests, catstests, regresstests (see src/input/Makefile)
# alltests, notests
TESTSET:=notests
BUILD:=partial
ACL2:=
COQ:=

#+end_src

*** The ENV variable
#+NAME: ENVAR
#+begin_src common-lisp :noweb yes

ENV:= \
ACL2=${ACL2} \
AWK=${AWK} \
BOOKS=${BOOKS} \
BUILD=${BUILD} \
BYE=${BYE} \
CC=${CC} \
CCF=${CCF} \
COMMAND=${COMMAND} \
COQ=${COQ} \
DAASE=${DAASE} \
DESTDIR=${DESTDIR} \
DOCUMENT=${DOCUMENT} \
EXTRACT=${EXTRACT} \
GCLDIR=${GCLDIR} \
GCLOPTS=${GCLOPTS} \
GCLVERSION=${GCLVERSION} \
INC=${INC} \
INT=${INT} \
LDF=${LDF} \
LISP=${LISP} \
LISPFLAVOR=${LISPFLAVOR} \
LSP=${LSP} \
MNT=${MNT} \
NOISE=${NOISE} \
O=${O} \
OBJ=${OBJ} \
PART=${PART} \
PATCH=${PATCH} \
PLF=${PLF} \
PROOFS=${PROOFS} \
RANLIB=${RANLIB} \
RUNTYPE=${RUNTYPE} \
SPAD=${SPAD} \
SPADBIN=${SPADBIN} \
SPD=${SPD} \
SRC=${SRC} \
SRCDIRS=${SRCDIRS} \
SUBPART=${SUBPART} \
SYS=${SYS} \
TANGLE=${TANGLE} \
TAR=${TAR} \
TESTSET=${TESTSET} \
TMP=${TMP} \
TOUCH=${TOUCH} \
UNCOMPRESS=${UNCOMPRESS} \
VERSION=${VERSION} \
WEAVE=${WEAVE} \
XLIB=${XLIB} \
ZIPS=${ZIPS} 

#+end_src

*** book
This stanza constructs the book from the original pamphlet file.
At this time there is no difference between the pamphlet file
and straight latex (intentionally). Thus we just need to make 
sure the correct directories are in place, copy the files, and
run latex over the pamphlet file.

#+NAME: book
#+begin_src common-lisp :noweb yes
book:
	@ echo 79 building the book as ${MNT}/${SYS}/doc/book.dvi 
	@ ${BOOKS}/untanglec ${SRC}/doc/book.org > ${MNT}/${SYS}/doc/book.pamphlet
	@ cp -pr ${SRC}/doc/ps ${MNT}/${SYS}/doc
	@ (cd ${MNT}/${SYS}/doc ; \
	  if [ .${NOISE} = . ] ; then \
	    ( latex book.pamphlet --interaction nonstopmode ; \
	      latex book.pamphlet --interaction nonstopmode ) ; \
	   else \
	    ( latex book.pamphlet --interaction nonstopmode >${TMP}/trace ; \
	      latex book.pamphlet --interaction nonstopmode >${TMP}/trace ) ; \
	  fi ; \
	  rm book.pamphlet ; \
	  rm book.toc ; \
	  rm book.log ; \
	  rm book.aux )
	@ echo 80 The book is at ${MNT}/${SYS}/doc/book.dvi 

#+end_src
*** tanglec.c
#+NAME: tanglec.c
#+begin_src c :noweb yes

tanglec: books/tanglec.c
	@echo t01 making tanglec from books/tanglec.c
	@( cd books ; gcc -o tanglec tanglec.c )

# The literate sources are .org; three small C tools tangle from them.
# orgtangle X.org [chunk] -> source directly (the default build path);
# untanglec X.org -> the exact .pamphlet bytes (PDF / via mode); srctangle is
# the dispatcher every rule calls (orgtangle by default, untanglec+tanglec when
# AXIOM_TANGLE_VIA_PAMPHLET=1).  Kept in sync with the committed root Makefile.
untanglec: books/untanglec.c
	@echo t02 making untanglec from books/untanglec.c
	@( cd books ; ${CC} -o untanglec untanglec.c )

orgtangle: books/orgtangle.c
	@echo t04 making orgtangle from books/orgtangle.c
	@( cd books ; ${CC} -o orgtangle orgtangle.c )

srctangle-tools: tanglec untanglec orgtangle
	@chmod +x ${BOOKS}/srctangle

#+end_src

*** src
We should recompile the world with the .fn information but not here.
\begin{verbatim}
	( for i in `find . -name "*.lsp"` ; \
	    do echo $$i ; touch $$i ; done )
	( for i in `find . -name "*.lisp"` ; \
	    do echo $$i ; touch $$i ; done )
	@echo 15a remaking ${SRC}/interp for performance
	@(cd src ; ${ENV} ${MAKE} )
\end{verbatim}

#+NAME: src
#+begin_src common-lisp :noweb yes
srcdir: ${SPD}/src/Makefile
	@echo 15 making ${SPD}/src 
	@( cd src ; ${ENV} ${MAKE} )

${SPD}/src/Makefile: ${SPD}/src/Makefile.org
	@echo 16 making ${SPD}/src/Makefile from ${SPD}/src/Makefile.org
	( cd src ; \
	   ${EXTRACT} Makefile.org ; \
	   cp Makefile.pdf ${MNT}/${SYS}/doc/src/src.Makefile.pdf )

libspadclean:
	@echo 17 cleaning ${OBJ}/${SYS}/lib     
	@rm -rf ${OBJ}/${SYS}/lib       
	@( cd src ; ${EXTRACT} Makefile.org )
	@( cd src ; ${ENV} ${MAKE} clean )
	@rm -f ${SPD}/src/Makefile ${SPD}/src/Makefile.dvi

#+end_src

*** src setup
#+NAME: srcsetup
#+begin_src common-lisp :noweb yes
srcsetup: ${SPD}/src/Makefile
	@echo 18 making ${SPD}/src 
	@( cd src ; ${ENV} ${MAKE} setup )

#+end_src

*** lsp
We delegate the details of constructing common lisp to the Makefiles in
the subtree. We need only ensure that the Makefiles are up to date.

When we first make GCL we the src/Makefile will create a marker file
called gcldir. This file has the same name as the stanza to create
GCL and thus will prevent GCL from rebuilding. We need to do this
since we have no control over the GCL makefiles.

The =${OBJ}/${SYS}/bin= directory is where the lisps get built.
**** LSPMakefile
We need to specialize the Makefile stanza based on the version
of Lisp we plan to use. At the moment there are 3 GCL versions
which run Axiom: 2.4.1, 2.5, and 2.6 These are incompatible versions
so we have different patches against them. The details are in
the lsp/Makefile.pamphlet file. Here we just decide which section
to choose. The default is 2.4.1 but if the GCLVERSION is changed
then the Makefile is rewritten to extract the later version.
It looks for a chunk name that matches the version number.
#+NAME: LSPMakefile
#+begin_src common-lisp :noweb yes
${LSP}/Makefile: ${LSP}/Makefile.org
	@echo 20 making ${LSP}/Makefile from ${LSP}/Makefile.org
	@( cd lsp ; \
	 ${EXTRACT} Makefile.org ; \
	 if [ "${GCLVERSION}" != "gcl-2.4.1" ] ; then \
	 ${BOOKS}/srctangle Makefile.org ${GCLVERSION} >Makefile ; \
	 fi ; \
	 cp Makefile.pdf ${MNT}/${SYS}/doc/src/lsp.Makefile.pdf )

#+end_src
Here we add mkdir -p =${OBJ}/${SYS}/lsp= because we need to rename the
=gcl_collectfn.lsp= back to collectfn.lsp. We also start adding support
for sys-proclaim.lsp and other dynamically collected proclaim information.

The obj/sys/bin dir is necessary to keep the compiled lisp image.
The obj/sys/lsp dir is necessary to keep collectfn and sys-proclaims.
The collectfn.lsp file is a special extension to GCL to collect type
information during a compile-file. This information gets written out
to a .fn file. These .fn files can be loaded and written out
as a file containing proclaims information. If this proclaims information
is available at compile time then the resulting function calls are much
more efficient. The sys-proclaims file contains type information
about standard common lisp function calls.

Under *LISPFLAVOR=sbcl* this target changes meaning. There is no
GCL to compile: the host Lisp is the system SBCL, and all this target
must do is provide it where the rest of the build expects to find the
host, namely =${OBJ}/${SYS}/bin/lisp= (the *LISPSYS* of
src/interp/Makefile.pamphlet, which pipes the depsys save form into
it). We write a two-line wrapper script there. The flags matter:
{\bf -{}-no-userinit -{}-no-sysinit} keep the user's sbclrc out of the
build, both for reproducibility and because an init file that starts
threads (a SLYNK server, say) would abort every image save ---
sb-ext:save-lisp-and-die refuses to dump a multithreaded image. This
was observed directly, not predicted: the migration spike in
books/bookvolMIGRATION.pamphlet failed exactly that way until the
init files were excluded.

Two further flags came out of the first full build attempt, each from
a watched failure. First, the GCL bin/lisp was never a bare Lisp:
lsp/Makefile.pamphlet loads books/tangle.lisp before its
save-system, so the host image carries the literate tangler, and
every recipe downstream pipes forms like
=(tangle "foo.pamphlet" "*" "foo.lisp")= into it. A bare SBCL
answered ``The function TANGLE is undefined''; the wrapper therefore
loads books/tangle.lisp, which is plain portable Common Lisp and
loads under SBCL unchanged. Second,
{\bf -{}-disable-debugger}: when that undefined-function error fired,
SBCL parked the whole build in its interactive debugger waiting on a
pipe that would never answer. A batch host must die loudly, not wait
politely; with the flag, any unhandled error aborts the recipe and
make reports it.
#+NAME: lsp
#+begin_src common-lisp :noweb yes
lspdir: ${LSP}/Makefile
	@echo 19 making ${LSP}
	@mkdir -p ${OBJ}/${SYS}/bin
	@mkdir -p ${OBJ}/${SYS}/lsp
ifeq (${LISPFLAVOR},sbcl)
	@echo =====================================
	@echo lsp USING SYSTEM SBCL AS HOST LISP
	@echo =====================================
	@echo '#!/bin/sh -' > ${OBJ}/${SYS}/bin/lisp
	@echo 'exec sbcl --no-userinit --no-sysinit --disable-debugger \
	  --load ${BOOKS}/tangle.lisp "$$@"' >> ${OBJ}/${SYS}/bin/lisp
	@chmod +x ${OBJ}/${SYS}/bin/lisp
else
	@echo =====================================
	@echo lsp BUILDING GCL COMMON LISP
	@echo =====================================
	(cd lsp ; ${ENV} DESTDIR= ${MAKE} gcldir )
	@(cp ${GCLDIR}/unixport/saved_gcl ${SPADBIN}/${GCLVERSION})
endif

<<LSPMakefile>>
lspclean:
	@echo 21 cleaning ${OBJ}/${SYS}/ccl
	@rm -rf ${LSP}/${GCLVERSION}
	@rm -rf ${INT}/ccl
	@rm -rf ${OBJ}/${SYS}/ccl
	@rm -rf ${LSP}/gcldir
	@rm -f ${LSP}/Makefile ${LSP}/Makefile.dvi

#+end_src
*** install
#+NAME: install
#+begin_src common-lisp :noweb yes
install:
	@echo 78 installing Axiom in ${DESTDIR}
	@mkdir -p ${DESTDIR}
	@cp -pr ${MNT} ${DESTDIR}
	@echo '#!/bin/sh -' >${COMMAND}
	@echo AXIOM=${DESTDIR}/mnt/${SYS} >>${COMMAND}
	@echo export AXIOM >>${COMMAND}
	@echo PATH='$${AXIOM}/bin':'$${PATH}' >>${COMMAND}
	@echo export PATH >>${COMMAND}
	@cat ${INT}/sman/axiom >>${COMMAND}
	@chmod +x ${COMMAND}
	@echo 79 Axiom installation finished.
	@echo
	@echo Please add $(shell dirname ${COMMAND}) to your PATH variable
	@echo Start Axiom with the command $(shell basename ${COMMAND})
	@echo 

#+end_src
*** document

Each file in the system is in pamphlet form. This stanza, which is not
executed by default, will walk the directories generating the
documentation for each file. These are dvi files and since they are
system-independent and machine-generated they live in the INT
subdirectory. In particular, we will build an INT/DOC subtree
mirroring the LSP and SRC subtrees. The INT/DOC
subtree can be removed with no ill effect. Since all of the pamphlet
files live in either the LSP or SRC subdirectories we make
sure the INT/DOC/LSP and INT/DOC/SRC directories exist.

#+NAME: document
#+begin_src common-lisp :noweb yes
document: 
	@echo 22 documenting files
	@(cd lsp ; ${ENV} ${MAKE} document )
	@(cd src ; ${ENV} ${MAKE} document )

#+end_src
*** clean
#+NAME: clean
#+begin_src common-lisp :noweb yes
clean: 
	@ echo 7 making a ${SYS} system, PART=${PART} SUBPART=${SUBPART}
	@ echo 8 Environment ${ENV}
	@ rm -f lsp/Makefile.dvi
	@ rm -f lsp/Makefile
	@ rm -f trace
	@ rm -f *~
	@ rm -f Makefile.${SYS}
	@ rm -rf ${MNT}
	@ rm -rf int
	@ rm -rf obj
	@ rm -rf mnt
	@ for i in `find src -name "Makefile"` ; do rm -f $i ; done
	@ for i in `find src -name "Makefile.dvi"` ; do rm -f $i ; done

#+end_src
** The Platform Makefiles

The Top Level Makefile examines the SPAD variable to determine
the target build platform. It sets up the general structure
of the world. Then it invokes one of these platform Makefiles. 
Each of these Makefiles sets several
environment variables that are specific to this platform.

**** The LDF variable 

The LDF variable is the generic loader flags. This gives information
about where various libraries are located on specific platforms. On
linux, for instance, the library libXpm.a is used by the graphics
routines. This library is usually found in /usr/X11R6/bin/libXpm.a. 
Thus, on the linux platform LDF is defined as
\begin{verbatim}
LDF=" -L/usr/X11R6/lib -L/usr/lib ${XLIB}/libXpm.a -lXpm"
\end{verbatim}

**** The AWK variable 

On most systems the gnu toolset is the default. Thus we can just use
'awk' and the program works. However, on some systems we need to
specify that we are using the gnu toolset, and we need to use
gawk instead of awk.

**** The PATCH variable 

On most systems the gnu toolset is the default. Thus we can just use
'patch' and the program works. However, on some systems we need to
specify that we are using the gnu toolset, and we need to use
gpatch instead of patch.

**** The O variable 
Various Common Lisp systems prefer certain filename extensions.
This defaults to ``o'' so a compile of foo.lisp becomes foo.o
but other systems prefer .fasl so a compile of foo.lisp becomes
foo.fasl. Change this based on the target lisp.

**** The LISP variable 
There are 3 kinds of "lisp" files in the Axiom build process.
The first are the "clisp" files. These are common lisp files
generated by the boot compiler. The second are the "lisp" files.
These are hand written common lisp code. The third are the "lsp"
files. These are files generated by GNU Common Lisp. The LISP
variable is used to name the third kind of files as this may
change when the underlying common lisp is changed.

**** The DAASE variable
Axiom uses 5 files, the *.daase files, which are called ``the
databases''. They contain cross-reference, signatures,
and other information needed by the interpreter and compiler.
When the system is being built from scratch these databases
need to exist. However, they get dynamically rebuilt after
the algebra files are compiled. The bootstrap versions of these
databases live in the src/share subdirectory. Axiom will
use the value of the shell variable DAASE to find its 
databases. If this variable is unbound it uses the standard
=${MNT}/${SYS}= path. Note that Axiom will append the string
/algebra to the value of DAASE. The default value setting
given here is:

=DAASE=${SRC}/share=

so =${SRC}/share/algebra/*.daase= will be the
Axiom bootstrap database files.

**** The XLIB variable
The XLIB variable tells us where the X11 libraries live.
Axiom needs to use libXpm.a to build the graph subdirectory.

**** The SRCDIRS variable
The SRCDIRS variable is used in the src/Makefile.pamphlet
to decide what directories to build on a given platform. This is
needed at the moment because certain functions do not yet work on
all platforms. 

**** The GCLVERSION variable 
GCLVERSION is the name of the GCL version. The one we used to
build the original version of the system is gcl-2.4.1. The system
will attempt to untar a file in the ZIPS directory with the
name GCLVERSION.tgz, cd to the GCLVERSION subdirectory and
do a ./configure followed by a make.

The GCLVERSION variable is also used to make the GCLDIR variable.
GCLDIR tells depsys where GCL lives. The depsys image needs to
load a file from GCL (cmpnew/collectfn.lsp) which is used to generate
optimizations for function calling in Axiom. This is handled automatically
by changing this variable.

If GCLVERSION is ``gcl-system'', then GCL is not built locally,
and it is assumed that the ``gcl'' command is available off the path.
IF this GCL is unsuitable for building Axiom then very bad things
will happen.

NOTE WELL: IF YOU CHANGE THIS YOU SHOULD ERASE THE lsp/Makefile FILE.
This will cause the build to remake the lsp/Makefile from the
lsp/Makefile.pamphlet file and get the correct version. If you
forget to erase the lsp/Makefile the wrong patches will be applied.

#+NAME: GCLVERSION
#+begin_src common-lisp :noweb yes
#GCLVERSION=gcl-2.4.1
#GCLVERSION=gcl-2.5
#GCLVERSION=gcl-2.5.2
#GCLVERSION=gcl-2.6.1
#GCLVERSION=gcl-2.6.2
#GCLVERSION=gcl-2.6.2a
#GCLVERSION=gcl-2.6.3
#GCLVERSION=gcl-2.6.5
#GCLVERSION=gcl-2.6.6
#GCLVERSION=gcl-2.6.7pre
#GCLVERSION=gcl-2.6.7
#GCLVERSION=gcl-2.6.8pre
#GCLVERSION=gcl-2.6.8pre2
#GCLVERSION=gcl-2.6.8pre3 
#GCLVERSION=gcl-2.6.8pre4
#GCLVERSION=gcl-2.6.8pre7
#GCLVERSION=gcl-cygwin
#GCLVERSION=gcl-2.6.9
#GCLVERSION=gcl-2.6.10
#GCLVERSION=gcl-2.6.11
#GCLVERSION=gcl-2.6.12
GCLVERSION=gcl-2.6.13pre
#+end_src

**** Selecting the host Lisp flavor

Historically the only host Lisp this build knew was the bundled GCL,
so ``which Lisp'' was never a question the Makefile had to answer.
The GCL-to-SBCL migration (see books/bookvolMIGRATION.pamphlet)
changes that: the same literate build must be able to host on either
Lisp while the port proceeds, with GCL remaining the default so that
existing platforms are not disturbed.

The *LISPFLAVOR* variable is that selector. It defaults to
*gcl*, which leaves every recipe exactly as it always was. Saying
\begin{verbatim}
make LISPFLAVOR=sbcl
\end{verbatim}
selects the system SBCL instead. Two things change under sbcl. First,
the compiled-object extension *O* becomes *fasl*: SBCL's
compile-file emits fasl files, not the .o object modules GCL's
C-backed compiler produces, and every dependency pattern keyed on
=${O}= follows automatically. Second, the *lspdir* target
stops building the bundled GCL and instead provides the system SBCL
as the build's host Lisp (see the lsp section). Source file
extensions are untouched: *LISP* stays *lsp* because the
written sources do not change dialect, only their compiled form does.

#+NAME: LISPFLAVOR
#+begin_src common-lisp :noweb yes
LISPFLAVOR?=gcl
ifeq (${LISPFLAVOR},sbcl)
O:=fasl
endif
#+end_src

**** The GCLOPTS configure variable
The GCLOPTS lisp requires some parameters 
for building which vary from system
to system. We create an environment variable here so we can add options
to the configure command in the lsp/Makefile.pamphlet.

#+NAME: GCLOPTS
#+begin_src common-lisp :noweb yes 
GCLOPTS="--enable-vssize=65536*2 --disable-xgcl --disable-tkconfig"
#+end_src
It turns out that we can successfully build GCL on many more systems
if we set the GCLOPTS to build a local BFD.

We are failing during build because "directoryp is undefined" along
with the message
\begin{verbatim}
Error: Cannot get relocated section contents
\end{verbatim}
#+NAME: GCLOPTS-LOCBFD
#+begin_src common-lisp :noweb yes
GCLOPTS="--enable-vssize=65536*2 --disable-xgcl --disable-tkconfig"
#+end_src
For the gcl-2.6.8pre7 version we move to using the custreloc option.
#+NAME: GCLOPTS-CUSTRELOC
#+begin_src common-lisp :noweb yes
GCLOPTS="--enable-vssize=65536*2 --disable-xgcl --disable-tkconfig"
#+end_src
For the MACOSX port we need the following options. The ``--disable-nls'' means 
that we will not be supporting natural language internationalization.
The ``--enable-maxpage'' has been eliminated because it causes build failures.
The ``--enable-machine'' parameter appears to be used by configure from the
setting of the ``canonical'' variable, which is in turn set by a shell script.
We need to add ``--enable-locbfd'' and ``--disable-dlopen'' due to the error
``unexec: not enough room for load commands for new \_\_DATA segments''.
#+NAME: GCLOPTS-MACPORT
#+begin_src common-lisp :noweb yes
GCLOPTS="--enable-vssize=65536*2 --disable-xgcl --disable-tkconfig"
#+end_src
*** Makefile.freebsd
#+NAME: Makefile.freebsd
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

####1 C related variables
INC:=${SPD}/src/include
PLF=BSDplatform
CCF="-O2 -pipe -fno-strength-reduce -D_GNU_SOURCE \
     -D${PLF} -I/usr/X11R6/include -I/usr/local/include -std=gnu89 -w"
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF="-L/usr/X11R6/lib -L/usr/local/lib"
O:=o

<<GCLOPTS-CUSTRELOC>>
<<ENVAR>>

all: srcsetup srcdir
	@echo 45 Makefile.FreeBSD called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
*** Makefile.windows
This is for the Windows port. We assume that the build will be done
using GCC under MSYS.

We've modified the GCLOPTS variable from the standard config in
two ways. First we add --enable-debug so more information is
available for testing and second we removed --enable-statsysbfd.

#+NAME: Makefile.windows
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

AWK=awk

####2 C related variables
INC:=${SPD}/src/include
PLF=MSYSplatform
CCF="-O2 -D_GNU_SOURCE -D${PLF} -std=gnu89 -w"
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF:=" -L/usr/X11R6/lib -L/usr/lib  -lXpm"
O:=o

SRCDIRS="bootdir interpdir sharedir algebradir etcdir docdir inputdir"
<<GCLOPTS-CUSTRELOC>>
<<ENVAR>>

all: srcsetup srcdir
	@echo 45 Makefile.windows called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
#+NAME: Makefile.slackware
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

####3 C related variables
INC:=${SPD}/src/include
PLF:=LINUXplatform
CCF:="-O2 -fno-strength-reduce -D_GNU_SOURCE -D${PLF} -I/usr/X11/include -std=gnu89 -w"
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF:=" -L/usr/X11R6/lib -L/usr/lib  -lXpm"
O:=o

<<ENVAR>>

all: srcsetup srcdir
	@echo 45 Makefile.slackware called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
*** Makefile.linux
#+NAME: Makefile.linux
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

####4 C related variables
INC:=${SPD}/src/include
PLF:=LINUXplatform
CCF:="-O2 -fno-strength-reduce -D_GNU_SOURCE -D${PLF} -I/usr/X11/include -std=gnu89 -w"
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF:=" -L/usr/X11R6/lib -L/usr/lib  -lXpm"
O:=o

<<GCLOPTS-CUSTRELOC>>
<<ENVAR>>

all: srcsetup srcdir
	@echo 45 Makefile.linux called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
*** Makefile.mandriva
#+NAME: Makefile.mandriva
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

####5 C related variables
INC:=${SPD}/src/include
PLF:=LINUXplatform
CCF:="-O2 -fno-strength-reduce -D_GNU_SOURCE -D${PLF} -I/usr/X11/include -std=gnu89 -w"
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF:=" -L/usr/X11R6/lib -L/usr/lib  -lXpm"
O:=o

<<GCLOPTS-CUSTRELOC>>
<<ENVAR>>

all: srcsetup srcdir
	@echo 45 Makefile.mandriva called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
*** Makefile.vector
#+NAME: Makefile.vector
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

####6 C Related variables
INC:=${SPD}/src/include
PLF:=LINUXplatform
CCF:="-O2 -fno-strength-reduce -D_GNU_SOURCE -D${PLF} -I/usr/X11/include -std=gnu89 -w"
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF:=" -L/usr/X11R6/lib -L/usr/lib  -lXpm"
O:=o

<<GCLOPTS-CUSTRELOC>>
<<ENVAR>>

all: srcsetup srcdir
	@echo 45 Makefile.linux called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
*** Makefile.redhat72
#+NAME: Makefile.redhat72
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

####7 C Related variables
INC:=${SPD}/src/include
PLF:=LINUXplatform
CCF:="-O2 -fno-strength-reduce -D_GNU_SOURCE -D${PLF} -I/usr/X11/include -std=gnu89 -w"
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF:=" -L/usr/X11R6/lib -L/usr/lib  -lXpm"
O:=o

<<GCLOPTS-CUSTRELOC>>
<<ENVAR>>

all: srcsetup srcdir
	@echo 45 Makefile.linux called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
*** Makefile.redhat9
#+NAME: Makefile.redhat9
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

####8 C Related variables
INC:=${SPD}/src/include
PLF:=LINUXplatform
CCF:="-O2 -fno-strength-reduce -D_GNU_SOURCE -D${PLF} -I/usr/X11/include -std=gnu89 -w"
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF:=" -L/usr/X11R6/lib -L/usr/lib  -lXpm"
O:=o

<<GCLOPTS-CUSTRELOC>>
<<ENVAR>>

all: srcsetup srcdir
	@echo 45 Makefile.linux called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
*** Makefile.debian
#+NAME: Makefile.debian
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

####9 C Related variables
INC:=${SPD}/src/include
PLF:=LINUXplatform
CCF:="-O2 -fno-strength-reduce -D_GNU_SOURCE -D${PLF} -I/usr/X11/include -std=gnu89 -w"
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF:=" -L/usr/X11R6/lib -L/usr/lib  -lXpm"
O:=o

<<GCLOPTS-CUSTRELOC>>
<<ENVAR>>

all: srcsetup srcdir
	@echo 45 Makefile.linux called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
*** Makefile.opensuse
#+NAME: Makefile.opensuse
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

####A C Related variables
INC:=${SPD}/src/include
PLF:=LINUXplatform
CCF:="-O2 -fno-strength-reduce -D_GNU_SOURCE -D${PLF} -I/usr/X11/include -std=gnu89 -w"
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF:=" -L/usr/X11R6/lib -L/usr/lib  -lXpm"
O:=o

<<GCLOPTS-CUSTRELOC>>
<<ENVAR>>

all: srcsetup srcdir
	@echo 45 Makefile.linux called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
*** Makefile.ubuntu
#+NAME: Makefile.ubuntu
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

####B C Related variables
INC:=${SPD}/src/include
PLF:=LINUXplatform
CCF:="-O2 -fno-strength-reduce -D_GNU_SOURCE -D${PLF} -I/usr/X11/include -std=gnu89 -w"
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF:=" -L/usr/X11R6/lib -L/usr/lib  -lXpm"
O:=o

<<GCLOPTS-CUSTRELOC>>
<<ENVAR>>

all: srcsetup srcdir
	@echo 45 Makefile.linux called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
*** Makefile.mint
#+NAME: Makefile.mint
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

####C C Related variables
INC:=${SPD}/src/include
PLF:=LINUXplatform
CCF:="-O2 -fno-strength-reduce -D_GNU_SOURCE -D${PLF} -I/usr/X11/include -std=gnu89 -w"
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF:=" -L/usr/X11R6/lib -L/usr/lib  -lXpm"
O:=o

<<GCLOPTS-CUSTRELOC>>
<<ENVAR>>

all: srcsetup srcdir
	@echo 45 Makefile.linux called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
*** Makefile.ubuntu64
#+NAME: Makefile.ubuntu64
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

####D C Related variables
INC:=${SPD}/src/include
PLF:=LINUXplatform
CCF:="-O2 -fno-strength-reduce -D_GNU_SOURCE -D${PLF} -I/usr/X11/include -std=gnu89 -w"
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF:=" -L/usr/X11R6/lib -L/usr/lib -lXpm"
O:=o

<<GCLOPTS-CUSTRELOC>>
<<ENVAR>>

all: srcsetup srcdir
	@echo 45 Makefile.linux called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
*** Makefile.centos
#+NAME: Makefile.centos
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

####E C Related variables
INC:=${SPD}/src/include
PLF:=LINUXplatform
CCF:="-O2 -fno-strength-reduce -D_GNU_SOURCE -D${PLF} -I/usr/X11/include -std=gnu89 -w"
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF:=" -L/usr/X11R6/lib -L/usr/lib  -lXpm"
O:=o

<<GCLOPTS-CUSTRELOC>>
<<ENVAR>>

all: srcsetup srcdir
	@echo 45 Makefile.linux called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
*** Makefile.macosxppc
#+NAME: Makefile.macosxppc
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

####F C Related variables
INC:=${SPD}/src/include
PLF:=MACOSXplatform
CCF:="-O2 -fno-strength-reduce -D_GNU_SOURCE -D${PLF} -I/usr/X11/include -std=gnu89 -w"
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF:=" -L/usr/X11R6/lib -L/usr/lib  -lXpm"
O:=o

<<GCLOPTS-MACPORT>>
<<ENVAR>>


all: srcsetup srcdir
	@echo 45 Makefile.macosxppc called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
*** Makefile.fedora
#+NAME: Makefile.fedora
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

####G C Related variables
INC:=${SPD}/src/include
PLF:=LINUXplatform
CCF:="-O2 -fno-strength-reduce -D_GNU_SOURCE -D${PLF} -I/usr/X11/include -std=gnu89 -w"
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF:=" -L/usr/X11R6/lib -L/usr/lib  -lXpm"
O:=o

<<GCLOPTS-CUSTRELOC>>
<<ENVAR>>


all: srcsetup srcdir
	@echo 45 Makefile.fedora called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
*** Makefile.fedora5
#+NAME: Makefile.fedora5
#+begin_src common-lisp :noweb yes
<<Makefile.fedora>>
#+end_src
*** Makefile.fedora6
#+NAME: Makefile.fedora6
#+begin_src common-lisp :noweb yes
<<Makefile.fedora>>
#+end_src
*** Makefile.fedora7
#+NAME: Makefile.fedora7
#+begin_src common-lisp :noweb yes
<<Makefile.fedora>>
#+end_src
*** Makefile.fedora8
#+NAME: Makefile.fedora8
#+begin_src common-lisp :noweb yes
<<Makefile.fedora>>
#+end_src
*** Makefile.fedora8-64
Fedora 8 on a 64 bit machine requires gcl-2.6.8pre2
#+NAME: Makefile.fedora8-64
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

####H C Related variables
INC:=${SPD}/src/include
PLF:=LINUXplatform
CCF:="-O2 -fno-strength-reduce -D_GNU_SOURCE -D${PLF} -I/usr/X11/include -std=gnu89 -w"
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF:=" -L/usr/X11R6/lib -L/usr/lib  -lXpm"
O:=o

<<GCLOPTS-CUSTRELOC>>
<<ENVAR>>


all: srcsetup srcdir
	@echo 45 Makefile.linux called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
*** Makefile.fedora9
#+NAME: Makefile.fedora9
#+begin_src common-lisp :noweb yes
<<Makefile.fedora>>
#+end_src
*** Makefile.fedora10
#+NAME: Makefile.fedora10
#+begin_src common-lisp :noweb yes
<<Makefile.fedora>>
#+end_src
*** Makefile.fedora11
#+NAME: Makefile.fedora11
#+begin_src common-lisp :noweb yes
<<Makefile.fedora>>
#+end_src
*** Makefile.fedora12
#+NAME: Makefile.fedora12
#+begin_src common-lisp :noweb yes
<<Makefile.fedora>>
#+end_src
*** Makefile.fedora13
#+NAME: Makefile.fedora13
#+begin_src common-lisp :noweb yes
<<Makefile.fedora>>
#+end_src
*** Makefile.gentoo
#+NAME: Makefile.gentoo
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

####D C Related variables
INC:=${SPD}/src/include
PLF:=LINUXplatform
CCF:="-O2 -fno-strength-reduce -D_GNU_SOURCE -D${PLF} -I/usr/X11/include -std=gnu89 -w"
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF:=" -L/usr/X11R6/lib -L/usr/lib  -lXpm"
O:=o

<<GCLOPTS-CUSTRELOC>>
<<ENVAR>>


all: srcsetup srcdir
	@echo 45 Makefile.linux called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
*** Makefile.fedora64
#+NAME: Makefile.fedora64
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

####I C Related variables
INC:=${SPD}/src/include
PLF:=LINUXplatform
CCF:="-O2 -fno-strength-reduce -D_GNU_SOURCE -D${PLF} -I/usr/X11/include -std=gnu89 -w"
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF="-L/usr/X11R6/lib64 -L/usr/local/lib64 -L/usr/openwin/lib64 -L/usr/lib64 "
O:=o

<<GCLOPTS-CUSTRELOC>>
<<ENVAR>>


all: srcsetup srcdir
	@echo 45 Makefile.linux called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
*** Makefile.fedora3
Fedora Core 3 needs special GCL options for local bfd.
#+NAME: Makefile.fedora3
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

####J C Related variables
INC:=${SPD}/src/include
PLF:=LINUXplatform
CCF:="-O2 -fno-strength-reduce -D_GNU_SOURCE -D${PLF} -I/usr/X11/include -std=gnu89 -w"
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF="-L/usr/X11R6/lib64 -L/usr/local/lib64 -L/usr/openwin/lib64 -L/usr/lib64 "
O:=o

<<GCLOPTS-LOCBFD>>
<<ENVAR>>


all: srcsetup srcdir
	@echo 45 Makefile.linux called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
*** Makefile.MACOSX
On the MAC OSX someone decided (probably a BSDism) to rename the
SIGCLD signal to SIGCHLD. In order to handle this in the 
low level C socket code (in particular, in =src/lib/fnct_key.c=)
we change the platform variable to be MACOSXplatform and create
this new stanza.

It appears that the MAC OSX does not include gawk or nawk by 
default so we change the AWK variable to use awk.

We need to add -I/usr/include/sys because =malloc.h= has been
moved on this platform. 

We need to search includes (``-I'') in /usr/include before 
/usr/include/sys because the MAC seems to search in a
different order than linux systems. The sys versions of 
the include files are broken, at least for Axiom use.
#+NAME: Makefile.MACOSX
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

AWK=awk

####K C Related variables
PLF=MACOSXplatform
CCF="-O2 -fno-strength-reduce -D_GNU_SOURCE -D${PLF} \
     -I/usr/X11/include -I/usr/include -I/usr/include/sys \
     -Wno-absolute-value -std=gnu89 -w" 
INC:=${SPD}/src/include
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF="-L/usr/X11R6/lib64 -L/usr/local/lib64 -L/usr/openwin/lib64 -L/usr/lib64 "
O:=o

# The platform line above resets O to o after ENVDEFAULTS has already
# applied the LISPFLAVOR selection, and ENVAR below snapshots the
# variables with immediate assignment -- so without re-applying the
# selector here, a LISPFLAVOR=sbcl build hands its sub-makes O=o and
# depsys compiles fasls under .o names the extensionless loader then
# cannot find (observed: "wrote clam.o ... Couldn't load clam").
# The re-application must sit between the platform reset and ENVAR.
<<LISPFLAVOR>>

<<GCLOPTS-MACPORT>>
<<ENVAR>>

all: srcsetup srcdir
	@echo 45 Makefile.linux called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
*** Makefile.BSD
On the MAC OSX someone decided (probably a BSDism) to rename the
SIGCLD signal to SIGCHLD. In order to handle this in the 
low level C socket code (in particular, in =src/lib/fnct_key.c=)
we change the platform variable to be MACOSXplatform and create
this new stanza.

It appears that the MAC OSX does not include gawk or nawk by 
default so we change the AWK variable to use awk.

We need to add -I/usr/include/sys because =malloc.h= has been
moved on this platform. 

We need to search includes (``-I'') in /usr/include before 
/usr/include/sys because the MAC seems to search in a
different order than linux systems. The sys versions of 
the include files are broken, at least for Axiom use.
#+NAME: Makefile.BSD
#+begin_src common-lisp :noweb yes

<<ENVDEFAULTS>>

AWK=awk

####K C Related variables
PLF=BSDplatform
CCF="-O2 -fno-strength-reduce -D_GNU_SOURCE -D${PLF} \
     -I/usr/X11/include \
     -Wno-absolute-value -std=gnu89 -w" 
INC:=${SPD}/src/include
CC:=gcc
XLIB:=/usr/X11R6/lib
LDF="-L/usr/X11/lib "
O:=o

<<GCLOPTS-MACPORT>>
<<ENVAR>>

all: srcsetup srcdir
	@echo 45 Makefile.linux called
	@echo 46 Environment : ${ENV} 
	@echo 47 finished system build on `date` | tee >lastBuildDate
	@- if [ "${TESTSET}" != "notests" ] ; \
	    then  grep "result FAILED" int/input/*.regress || true ; fi

<<literate commands>>
<<srcsetup>>
<<src>>
<<lsp>>
<<document>>
<<clean>>

#+end_src
\begin{thebibliography}{99}
\bibitem{1} CMUCL *http://www.cons.org/cmucl*
\bibitem{2} GCL *http://savannah.gnu.org/projects/gcl*
\bibitem{3} Codemist Ltd, ``Alta'', Horsecombe Vale Combs Down
Bath BA2 5QR UK Tel. +44-1225-837430 
*http://www.codemist.co.uk*
\bibitem{5} \$SPAD/zips/advi-1.2.0.tar.gz, the advi source tree
\end{thebibliography}
\end{document}

