
#+NAME: Geddes
#+begin_src common-lisp :noweb yes
)abbrev package GEDDES Geddes
++ Author: Mark Botch
++ Date Created: 2014
++ Description:
++ These are Axiom implementation of algorithms from [Geddes 92]
Geddes(): Exports == Implementation where
 EEA ==> Record(gcd:Integer,s:Integer,t:Integer)
 Exports ==> with
 
  Euclid: (Integer,Integer) -> Integer
    ++ Euclid algorithm from [Geddes 92], p 34
  ExtendedEuclidean: (Integer,Integer) -> EEA
    ++ Extended Euclidean algorithm from [Geddes 92], p 36

 Implementation ==> add

<<Geddes:Euclid>>
<<Geddes:ExtendedEuclidean>>

#+end_src
* Euclidean Algorithm

[cite:@Gedd92] p 34\\
*procedure* Euclid($a$,$b$)
\begin{addmargin}{1em}
-- Compute $g=GCD(a,b)$, where $a$ and $b$\\
-- are from a Euclidean domain D\\
$c \leftarrow n(a); d \leftarrow n(b)$\\
*while* $d \ne 0$ *do*\{
\begin{addmargin}{1em}
$r \leftarrow rem(c,d)$\\
$c \leftarrow d$\\
$d \leftarrow r$\}
\end{addmargin}
$g \leftarrow n(c)$\\
*return*(g)
\end{addmargin}
*end*

*** Geddes:Euclid
#+NAME: Geddes:Euclid
#+begin_src common-lisp :noweb yes
  Euclid(a:Integer,b:Integer):Integer ==
    c:Integer:=unitCanonical(a)
    d:Integer:=unitCanonical(b)
    while d ~= 0 repeat
      r:Integer:= c rem d
      c:=d
      d:=r
    c

#+end_src

*** Background

The Euclidean GCD function tries to compute the largest number that
divides both arguments. This isn't unique since $30=5\times 6=-5\times -6$.
To make it unique we define a unit (essentially the sign in the Integer).
When we extract the sign then $\{6, -6\}$ are essentially the same and
are called ``associates''. 

Having put the associates together we pick one by rule and call it the
canonical element. The rule for the Integers is to take the absolute
value so 6 is the canonical element for the associates $\{6, -6\}$.
We call this function *unitCanonical* although it is simply
the absolute value function in the domain Integer. Indeed, in 
*Volume 10.3: Domains* we find this line in the domain *Integer*:
#+begin_example
      unitCanonical x == abs x
#+end_example

*** Example

Euclid's algorithm collects the largest set of common factors. So for
18 and 30 we see:
\[18 = 2 \times 3 \times 3\]
and
\[30 = 2 \times 3 \times 5\]
and the common set of factors is
\[ 6 = 2 \times 3 \]

Rather than factor the numbers it is more efficient to divide the
two numbers which will yield a quotient and a remainder. So
in this case:
#+begin_example
c:=18
d:=30
  r:= c rem d -> 18 rem 30 -> 18
  c:= 30
  d:= 18
  r:= c rem d -> 30 rem 18 -> 12
  c:= 18
  d:= 12
  r:= c rem d -> 18 rem 12 -> 6
  c:= 12
  d:= 6
  r:= c rem d -> 12 rem 6 -> 0
  c:= 6
  d:= 0
result is c -> 6
#+end_example

Since the quotient and remainder will share the same common factors
as the original numbers we can continue this division loop until
the result of the remainder is 0. If the only factor in common is 1
then the numbers are called ``relatively prime''. Otherwise, as
above, we end up with the largest number composed of the common factors.

* Extended Euclidean

[cite:@Gedd92] p 36\\
*procedure* ExtendedEuclidean$(a,b; s,t)$
\begin{addmargin}{1em}
-- Given $a$ and $b$ in a Euclidean domain D, compute\\
-- $g = GCD(a,b)$ and also compute elements $s,t \in D$\\
-- such that $g=sa+tb$\\
$c \leftarrow n(a); d \leftarrow n(b)$\\
$c_1 \leftarrow 1; d_1 \leftarrow 0$\\
$c_2 \leftarrow 0; d_2 \leftarrow 1$\\
*while* $d \ne 0$ *do* \{
\begin{addmargin}{1em}
$q \leftarrow quo(c,d); r \leftarrow c-q\cdot d$\\
$r_1 \leftarrow c_1-q\cdot d_1; r_2 \leftarrow c_2-q\cdot d_2$\\
$c \leftarrow d; c_1 \leftarrow d_1; c_2 \leftarrow d_2$\\
$d \leftarrow r; d_1 \leftarrow r_1; d_2 \leftarrow r_2$ \}
\end{addmargin}
; Normalize GCD\\
$g \leftarrow n(c)$\\
$s \leftarrow c_1 / (u(a)\cdot u(c)); t \leftarrow c_2 / (u(b)\cdot u(c))$\\
*return*(g)
\end{addmargin}
*end*

*** Geddes:ExtendedEuclidean
#+NAME: Geddes:ExtendedEuclidean
#+begin_src common-lisp :noweb yes
  ExtendedEuclidean(a:Integer,b:Integer):EEA ==
    c:Integer:=unitCanonical(a)
    d:Integer:=unitCanonical(b)
    c1:Integer:=1
    d1:Integer:=0
    c2:Integer:=0
    d2:Integer:=1
    while d ~= 0 repeat
      q:Integer:= c quo d
      r:Integer:= c-q*d
      r1:Integer:= c1-q*d1
      r2:Integer:= c2-q*d2
      c  := d
      c1 := d1
      c2 := d2
      d  := r
      d1 := r1
      d2 := r2
    t1:Integer:= unitCanonical(c)
    t2:Integer:= c1 quo (unitNormal(a).unit*unitNormal(c).unit)
    t3:Integer:= c2 quo (unitNormal(b).unit*unitNormal(c).unit)
    [t1,t2,t3]
      

#+end_src

*** Background

Since we are doing simple assignments the ExtendedEuclidean
algorithm simply computes the $s$ and $t$ coefficients such that
a result $g=GCD(a,b)$ can be expressed as a linear 
combination of elements. So
\[t1:=ExtendedEuclidean(18,30) 
{\rm\ yields\ } [gcd= 6,s= 2,t= - 1]\]
and
\[ g = s\times a + t\times b -> 6 = 2\times 18 + (-1)\times 30 \]

Here we introduce two functions, *quo* and *unitNormal*.

The *quo* function is defined in *Volume 10.2: Domains* in
the domain *Integer* as
#+begin_example
   x quo y == QUOTIENT2(x,y)$Lisp
#+end_example
which resolves to the Lisp function in *Volume 5: Interpreter*
#+begin_example
   (defun quotient2 (x y)
     (values (truncate x y)))
#+end_example
which will return the integer portion of an integer division,
ignoring the fractional portion.

The *unitNormal* function in *Volume 10.2: Categories*
in the category *IntegralDomain* returns a portion of a Record.
The Record is defined as:
#+begin_example
   Record(unit:%,canonical:%,associate:%)
#+end_example
holding three pieces of information, the unit, the canonical element,
and the set of associates. We only need the unit information so we
access the record structure using the unit selector thus:
#+begin_example
   resultRecord.unit
#+end_example

The actual definition of *unitNormal* used here comes from 
*Volume 10.3: Domains* in domain *Integer* which defines it as
#+begin_example
   UCA ==> Record(unit:%,canonical:%,associate:%)
   unitNormal x ==
     x < 0 => [-1,-x,-1]$UCA
     [1,x,1]$UCA
#+end_example
which for the value $-6$ would resolve to 
#+begin_example
   [unit= - 1,canonical= 6,associate= - 1]
#+end_example
giving
#+begin_example
   unitNormal(-6).unit -> -1
#+end_example
and, as above, the *unitCanonical* function is just the absolute
value.

We use the *quo* operation at the final step rather than division.
Integer is not a Field so the operation isn't available. The division
operator would come from the domain *Fraction(Integer)* with the
signature
#+begin_example
   ?/? : (Integer,Integer) -> %
#+end_example
which takes two integers and returns an element of Fraction(Integer)
which is not what we want at the result. We know that the Integer
unit can only be $\pm 1$ so we use the *quo* operation from
*Integer*  to form the quotient we need, with the signature
#+begin_example
   ?quo? : (%,%) -> % 
#+end_example

*** Example
#+begin_example
ExtendedEuclidean(18,30)
  c   d  c1  d1  c2  d2   q   r  r1  r2   c   c1  c2   d  d1  d2
 18  30   1   0   0   1   0  18   1   0   30   0   1  18   1   0
                          1  12  -1   1   18   1   0  12  -1   1
                          1   6   2  -1   12  -1   1   6   2  -1
                          2   0  -5   3    6   2  -1   0  -5   3
 unitNormal(a) -> unitNormal(18) -> 1
 unitNormal(b) -> unitNormal(30) -> 1
 unitNormal(c) -> unitNormal(6) -> 1
 t1:=unitCanonical(c) -> unitCanonical(6) -> 6
 t2:=c1 quo (unitNormal(a).unit*unitNormal(c).unit) -> 2/1 -> 2
 t3:Integer:= c2 quo (unitNormal(b).unit*unitNormal(c).unit) -> -1/1 -> -1
 [gcd= 6,s= 2,t= - 1]
#+end_example


* Primitive Euclidean

[cite:@Gedd92] p 57\\
*procedure* PrimitiveEuclidean$(a(x),b(x))$
\begin{addmargin}{1em}
-- Given polynomials $a(x), b(x) \in D[x]$\\
-- where D is a UFD, we compute\\
-- $g(x)=GCD(a(x),b(x))$\\
$c(x) \leftarrow pp(a(x)); d(x) \leftarrow pp(b(x))$\\
*while* $d(x) \ne 0$ *do* \{
\begin{addmargin}{1em}
$r(x) \leftarrow prem(c(x),d(x))$\\
$c(x) \leftarrow d(x)$\\
$d(x) \leftarrow pp(r(x))$ \}
\end{addmargin}
$\gamma \leftarrow GCD(cont(a(x)),cont(b(x)))$\\
$g(x) \leftarrow \gamma c(x)$\\
*return*($g(x)$)
\end{addmargin}
*end*

*** Background

*** Example

* Multiprecision Integer Multiplication

[cite:@Gedd92] p 113\\
*procedure* BigIntegerMultiply($a$,$b$,$B$)
\begin{addmargin}{1em}
-- Given two multiprecision integers $a$ and $b$ of\\
-- lengths $m$ and $n$ with base $B$, we determine\\
-- $c=a\cdot b = c_0+c_1B+\cdots+c_{m+n-1}B^{m+n-1}$\\
*for* $i$ *from* 0 *to* $m-1$ *do* $c_i \leftarrow 0$\\
*for* $k$ *from* 0 *to* $n-1$ *do* \{
\begin{addmargin}{1em}
$carry \leftarrow 0$\\
*for* $i$ *from* 0 *to* $m-1$ *do* \{
\begin{addmargin}{1em}
$temp \leftarrow a_i\cdot b_k + c_{i+k} + carry$\\
$c_{i+k} \leftarrow rem(temp,B)$\\
$carry \leftarrow quo(temp,B)$
\end{addmargin}
$c_{k+m} \leftarrow carry$ \}
\end{addmargin}
*return*$(c_0+c_1B+\cdots+c_{m+n-1}B^{m+n-1})$
\end{addmargin}
*end*

*** Background

*** Example

* Karatsuba's Multiplication

[cite:@Gedd92] p 113\\
*procedure* Karatsuba$(a,b,n)$
\begin{addmargin}{1em}
-- Given multiprecision integers $a$ and $b$ with $n$ digits\\
-- and base $B$ we compute their product $c=a\cdot b$\\
-- The size $n$ must be a power of 2\\
*if* $n=1$ *then return*$(a\cdot b)$\\
*else* \{
\begin{addmargin}{1em}
$c \leftarrow sign(a) \cdot sign(b)$\\
$d \leftarrow |a|; b^\prime \leftarrow |b|$\\
$a_1 \leftarrow first  n/2  digits of  d$\\
$a_2 \leftarrow last  n/2  digits of  d$\\
$b_1 \leftarrow first   digits of  b^\prime$\\
$b_2 \leftarrow last  n/2  digits of  b^\prime$\\
$m1 \leftarrow Karatsuba(a1,b1,n/2)$\\
$m2 \leftarrow Karatsuba(a1-a2,b2-b1,n/2)$\\
$m3 \leftarrow Karatsuba(a2,b2,n/2)$\\
$c \leftarrow c\cdot (m1\cdot B^n+(m1+m2+m3)\cdot B^{n/2}+m3)$\\
*return*$(c)$ \}
\end{addmargin}
\end{addmargin}
*end*

*** Background

*** Example

* Polynomial Trial Division

[cite:@Gedd92] p 122\\
*procedure* TrialDivision$(a(x),b(x),m,n)$
\begin{addmargin}{1em}
-- Given two polynomials $a(x)$ and $b(x)$ with degrees $m$ and $n$ with\\
-- $m \ge n$, determine if $b()$ divides into $a(x)$ by trial division at the\\
-- points $x_0,...,x_m$. If true then return the quotient $c(x)$\\
*for* i *from* 0 *to* m *do* $\xi_i=a(x_i)/b(x_i)$\\
$c(x) \leftarrow PolyInterp(\xi_0,...,\xi_m)$\\
*if* $deg(c(x))=m-n$ *then return*$(c(x))$\\
*else return*(/does not divide/)
\end{addmargin}
*end*

*** Background

*** Example

Ordinary multiplication of 25 x 63:
#+begin_example
     
     25
  x  63

has the steps

  3  x  5 =   15
  3  x 20 =   60
  60 x  5 =  300
  60 x 20 = 1200

and then

  15 + 60 + 300 + 1200 = 1575

So we have 4 multiplications and 3 additions


#+end_example

* Fast Fourier Transform

[cite:@Gedd92] p 128\\
*procedure* FFT$(N,\varpi,a(x))$
\begin{addmargin}{1em}
-- Given $N$, a power of 2, $\varpi$ a primitive $N$-th root of\\
-- unity and $a(x)$ a polynomial of degree $\le N-1$, we calculate\\
-- the $N$ components of the Fourier transform of $a(x)$
*if* $N=1$ *then* $A_0 \leftarrow a_0$\\
*else* \{\\
\begin{addmargin}{1em}
$\displaystyle{}b(x)\leftarrow \sum_{i=0}^{N/2-1} a_{2i}\cdot x^i;  c(x) \leftarrow \sum_{i=0}^{N/2-1} a_{2i+1}\cdot x^i$\\
$B \leftarrow FFT(N/2,\omega^2,b(x));$ $C \leftarrowFFT(N/2,\omega^2,c(x))$\\
*for* $i$ *from* 0 *to* $N/2-1$ *do* \{
\begin{addmargin}{1em}
$A_i \leftarrow B_i+\omega^i \cdot C_i$\\
$A_{N/2+i} \leftarrow B_i-\omega^i \cdot C_i$ \}\}
\end{addmargin}
\end{addmargin}
*return*($(A_0,A_1,\cdots,A_{N-1})$)
\end{addmargin}
*end*

*** Background

*** Example

* Fast Fourier Polynomial Multiplication

[cite:@Gedd92] p 132\\
*procedure* FFTMultiply$(a(x),b(x),m,n)$
\begin{addmargin}{1em}
-- Given polynomials $a(x)$ and $b(x)$ of degree $m$ and $n$\\
-- calculate $c(x)=a(x)\cdot b(x)$ using FFTs\\
$N \leftarrow $ first power of 2 greater than $m+n$\\
$\omega \leftarrow $ primitive $N$-th root of unity\\
$A \leftarrow FFT(N,\omega,a(x))$\\
$B \leftarrow FFT(N,\omega,b(x))$\\
*for* $i$ *from* 0 *to* $N-1$ *do* $C_i=A_i\cdot B_i$\\
$c \leftarrow N^{-1}\cdot FFT(N,\omega^{-1},C(x))$\\
$c(x) \leftarrow \sum_{i=0}^{N-1} c_ix^i$\\
*return*($c(x)$)
\end{addmargin}
*end*

*** Background

*** Example

* Newton's Method for Power Series Inversion

[cite:@Gedd92] p 140\\
*procedure* FastNewtonInversion$(a(x),n)$\\
\begin{addmargin}{1em}
-- Given a power series $a(x)$ in $x$ with $a(0) = a_0 \ne 0$\\
-- find the first $2^n$ terms of the power series $1/a(x)$.\\
$y \leftarrow 1/a_0$\\
*for* $k$ *from* 0 *to* $n-1$ *do*
\begin{addmargin}{1em}
$y \leftarrow y\cdot (2-y\cdot a(x))  mod  x^{2^{k+1}}$
\end{addmargin}
*return*($y$)
\end{addmargin}
*end*

*** Background

*** Example

* Newton's Method for Solving $P(y)=0$
[cite:@Gedd92] p 144\\
*procedure* NewtonSolve$(P(y),y_0,n)$
\begin{addmargin}{1em}
-- Given $P(y) \in F[[x]][y]$, and a point $y_0$ satisfying\\
-- $P(y_0)=0  mod x$ and $P^\prime(y_0) \ne 0$, we determine the\\
-- first $2^n$ terms of a solution to $P(y)=0$ via Newton's method\\
$y \leftarrow y_0$\\
*for* $k$ *from* 0 *to* $n-1$ *do*
\begin{addmargin}{1em}
$y \leftarrow y-(P(y)\cdot P^\prime(y)^-1 mod x^{2^{k+1}}$
\end{addmargin}
*return*$(y)$
\end{addmargin}
*end*

*** Background

*** Example

* Garner's Chinese Remainder
[cite:@Gedd92] p 180\\
*procedure* IntegerCRA$((m_0,...,m_n),(u_0,...,u_n))$\\
\begin{addmargin}{1em}
 -- Given positive moduli $m_i \in *Z* (0 \le i \le n)$ which are pairwise\\
 -- relatively prime and given corresponding residues $u_i \in *Z*_{m_i}$\\
 -- computing the unique integer $u \in *Z*_m$ (where $m=\prod m_i$) such\\
 -- that $u \equiv u_i (mod m_i), i=0,1,...,n$  

-- Step 1: Compute the required inverses using a procedure\\
--  reciprocal$(a,q)$ which computes $a^{-1}(mod q)$\\
*for* $k$ *from* 1 *to* $n$ *do* \{
\begin{addmargin}{1em}
$product \leftarrow \phi_{m_k}(m_0)$\\
*for* $i$ *from* 1 *to* $k-1$ *do*
\begin{addmargin}{1em}
$product \leftarrow \phi_{m_k}(product\cdot m_i)$
\end{addmargin}
$\gamma \leftarrow reciprocal(product,m_k)$ \}
\end{addmargin}

-- Step 2: Compute the mixed radix coeffs \{$v_k$\}\\
$v_0 \leftarrow u_0$\\
*for* $k$ *from* 1 *to* $n$ *do* \{
\begin{addmargin}{1em}
$temp \leftarrow v_{k-1}$\\
*for* $j$ *from* $k-2$ *to* 0 *by* -1 *do* 
\begin{addmargin}{1em}
$temp \leftarrow \phi_{m_k}(temp\cdot m_j+v_j)$
\end{addmargin}
$v_k \leftarrow \phi_{m_k}((u_k-temp)\cdot \gamma_k)$ \}
\end{addmargin}

-- Step 3: Convert from mixed radix representation\\
-- to standard representation\\
$u \leftarrow v_n$\\
*for* $k$ *from* $n-1$ *to* 0 *by* -1 *do*
\begin{addmargin}{1em}
$u \leftarrow u\cdot m_k+v_k$
\end{addmargin}
*return*$(u)$
\end{addmargin}
*end*

*** Background

*** Example

* Newton Interpolation
[cite:@Gedd92] p 188\\
*procedure* NewtonInterp$((\alpha_0,...,\alpha_v)(u_0,...,u_v))$
\begin{addmargin}{1em}
-- Let $D=*Z*_p[y]$ denote a domain of polynomials in $v \ge 0$\\
-- indeterminates $y=(y_1,...,y_v)$ over a finite field $*Z*_p$\\
-- ($D=*Z*_p$ in case $v=0$). Given distinct evaluation points
$\alpha_i \in *Z*_p$\\
-- $(0 \le i \le n)$ and given corresponding values 
$u_i \in D (0 \le i \le n)$\\
-- compute the unique polynomial $u(x) \in D[x]$ such that 
deg$(u(x)) \le n$\\
-- and $u(\alpha_i)=u_i, i=0,1,...,n$

-- Step 1: Compute the required inverses using a procedure\\
--  reciprocal$(a,q)$ which computes $a^{-1}(mod q)$\\
*for* $k$ *from* 1 *to* $n$ *do* \{
\begin{addmargin}{1em}
$product \leftarrow \phi_p(\alpha_k-\alpha_0)$\\
*for* $i$ *from* 1 *to* $k-1$ *do*
\begin{addmargin}{1em}
$product \leftarrow \phi_p(product \cdot (\alpha_k-\alpha_i))$
\end{addmargin}
$\gamma_k \leftarrow reciprocal(product,p)$ \}
\end{addmargin}
-- Step 2: Compute the Newton coefficients \{$v_k$\}\\
$v_0 \leftarrow u_0$\\
*for* $k$ *from* 1 *to* $n$ *do* \{
\begin{addmargin}{1em}
$temp \leftarrow v_{k-1}$\\
*for* $j$ *from* $k-2$ *to* 0 *by* -1 do
\begin{addmargin}{1em}
$temp \leftarrow \phi_p(temp \cdot (\alpha_k-\alpha_j)+v_j)$
\end{addmargin}
$v_k \leftarrow \phi_p((u_k-temp)\cdot \gamma_k)$ \}
\end{addmargin}
-- Step 3: Convert from Newton form to standard form\\
$u \leftarrow v_n$\\
*for* $k$ *from* $n-1$ *to* 0 *by* -1 *do*
\begin{addmargin}{1em}
$u \leftarrow \phi_p(u \cdot (x-\alpha_k)+v_k)$
\end{addmargin}
*return*($u(x)$)
\end{addmargin}
*end*

*** Background

*** Example

* Univariate Hensel Lifting
[cite:@Gedd92] p 233\\
*procedure* UnivariateHensel$(a,p,u^{(1)},w^{(1)},B,\gamma)$
\begin{addmargin}{1em}
-- INPUT\\
-- (1) A primitive polynomial $a(x) \in *Z*[x]$\\
-- (2) A prime integer $p$ which does not divide lcoeff($a(x)$)\\
-- (3) Two relatively prime polynomials 
$u^{(1)}(x),w^{(1)}(x) \in *Z*_p[x]$ such that\\
--  $a(x) \equiv u^{(1)}(x)w^{(1)}(x)(mod p)$\\
-- (4) An integer $B$ which bounds the magnitudes of all integer coefficients\\
-- appearing in $a(x)$ and in any of its possible factors with degrees\\
-- not exceeding max\{deg($u^{(1)}(x)$),deg($w^{(1)}(x)$)\}\\
-- (5) Optionally, an integer $\gamma \in *Z*$ which is known to be a
multiple of\\
-- lcoeff($u(x)$), where $u(x)$ (see OUTPUT) below) is one of the 
factors of\\
-- $a(x)$ in *Z*[x] to be computed.\\
-- OUTPUT\\
-- (1) If there exist polynomials $u(x),w(x) \in *Z*[x]$ such that\\
--  $a(x)=u(x)w(x) \in *Z*[x]$\\
-- and\\
--  *n*$(u(x))\equiv *n*(u^{(1)}(x)) (mod p)$,
$*n*(w(x)) \equiv *n*(w^{(1)}(x))(mod p)$\\
-- where *n* denotes the normalization 
"make the polynomial monic as an\\
-- element of the domain $*Z*_p[x]$", then $u(x)$ and $w(x)$ will
be computed.\\
-- (2) Otherwise, the value returned will signal "no such factorization"\\

-- 1. Define a new polynomial and its modulo $p$ factors\\
$\alpha \leftarrow lcoeff(a(x))$\\
*if* $\gamma$ is undefined *then* $\gamma \leftarrow \alpha$\\
$a(x) \leftarrow \gamma\cdot a(x)$\\
$u^{(1)}(x) \leftarrow \phi_p(\gamma\cdot *n*(u^{(1)}(x)))$\\
$w^{(1)}(x) \leftarrow \phi_p(\alpha\cdot *n*(w^{(1)}(x)))$

-- 2. Apply extended Euclidean algorithm to 
$u^{(1)}(x),w^{(1)}(x) \in *Z*_p[x]$\\
$s(x),t(x) \leftarrow $ polynomials in $*Z*_p[x]$ computed by the extended euclidean algorithm such that\\
  $s(x)u^{(1)}(x)+t(x)w^{(1)}(x) \equiv 1 (mod  p)$\\

-- 3. Initialization for the iteration\\
$u(x) \leftarrow replace\_lc(u^{(1)}(x),\gamma)$\\
$w(x) \leftarrow replace\_lc(w^{(1)}(x),\alpha)$\\
$e(x) \leftarrow a(x)-u(x)\cdot w(x)$\\
$modulus \leftarrow p$

-- 4. Iterate until either the factorization in $*Z*[x]$ is obtained or\\
--  else the bound on /modulus/ is reached.\\
*while* $e(x) \ne 0$ *and* $modulus < 2\cdot B\cdot \gamma$ *do* \{
\begin{addmargin}{1em}
-- 4.1 Solve in the domain $*Z*_p[x]$ the polynomial equation\\
--  $\sigma(x)u^{(1)}(x)+\tau(x)w^{(1)}(x) \equiv c(x)(mod p)$\\
--  where $c(x) = e(x)/modulus$\\
$c(x) \leftarrow e(x)/modulus$\\
$\tilde{\sigma}(x) \leftarrow \phi_p(s(x)\cdot c(x))$\\
$\tilde{\tau}(x) \leftarrow \phi_p(t(x)\cdot c(x))$\\
$q(x),r(x) \leftarrow $ polynomials in $*Z*_p[x]$ such that\\
\hspace*{1cm} $\tilde{\sigma}(x) = w^{(1)}(x)q(x)+r(x) \in *Z*_p[x]$\\
$\sigma(x) \leftarrow r(x)$\\
$\tau(x) \leftarrow \phi_p(\tilde{\tau}(x)+q(x)\cdot u^{(1)}(x))$\\

-- 4.2 Update the factors and compute the error\\
$u(x) \leftarrow u(x)+\tau(x)\cdot modulus;$\\
$w(x) \leftarrow w(x)+\sigma(x)\cdot modulus$\\
$e(x) \leftarrow a(x)-u(x)\cdot w(x)$\\
$modulus \leftarrow modulus\cdot p$ \}
\end{addmargin}
-- 5. Check the termination status\\
*if* $e(x)=0$ *then* \{
\begin{addmargin}{1em}
-- factorization obtained - remove contents\\
$\delta \leftarrow cont(u(x))$\\
$u(x) \leftarrow u(x)/\delta$\\
$w(x) \leftarrow w(x)/(\gamma/\delta)$\\
-- Note: $a(x) \leftarrow a(x)/\gamma$
would restore $a(x)$ to its input value \}\\
*return*$(u(x),w(x))$
\end{addmargin}
*else return*(/no such factorization exists/)
\end{addmargin}
*end*

*** Background

*** Example

* Multivariate Polynomial Diophantine Equations
[cite:@Gedd92] p 268\\
*procedure* MultivariateDiophant$(a,c,I,d,p,k)$\\
\begin{addmargin}{1em}
-- Solve in the domain $*Z*_{p^k}[x_1,...,x_v]$ the multivariate
polynomial\\
-- diophantine equation\\
-- $\sigma_1\times b_1+\cdots+\sigma_r\times b_r 
\equiv c (mod <I^{d+1},p^k>)$\\
-- where, in terms of the given list of polynomials $a_1,...,a_r$,\\
-- the polynomials $b_i, i=1,...,r$, are defined by:\\
-- $b_i=a_1\times\cdots\times a_{i-1}\times a_{i+1}\times\cdots\times a_r$.\\
-- The unique solution $\sigma_i, i=1,...,r$ will be computed such that\\
-- degree$(\sigma_i,x_1) < $degree$(a_i,x_1)$\\
--\\
-- Conditions: $p$ must not divide lcoeff($a_i$ mod I),$i=1,...,r$.\\
-- $a_i mod <I,p>,i=1,...,r$ must be pairwise relatively prime\\
-- in $*Z*_p[x_1]$; 
and degree$(c,x_1) <$ sum(degree$(a_i,x_1),i-1,...,r)$\\
--\\
-- INPUT\\
-- (1) A list $a$ of $r > 1$ polynomials in the domain 
$*Z*_{p^k}[x_1,...,x_v]$\\
-- (2) A polynomial $c \in *Z*_{p^k}[x_1,...,x_v]$\\
-- (3) $l$, a list of equations 
$[x_2=\alpha_2,x_3=\alpha_3,...,x_v=\alpha_v]$\\
-- (possibly null, in which case it is a univariate problem)\\
-- representing an evaluation homomorphism;\\
-- mathematically, we view it as the ideal\\
--  I=$<x_2-\alpha_2,x_3-\alpha_3,...,x_n-\alpha_n>$\\
-- (4) A nonnegative integer $d$ specifying the maximum total degree\\
-- with respect to $x_2,...,x_v$ of the desired result\\
-- (5) A prime integer $p$\\
-- (6) A positive integer $k$ specifying that the coefficient arithmetic\\
-- is to be performed modulo $p^k$\\
--\\
-- OUTPUT
-- The value returned is the list $\sigma = [\sigma_1,...,\sigma_r]$\\
--\\
-- Remark: The mod operations must use the symmetric representation\\
--\\
-- 1. Initialization\\
$r \leftarrow$ number of polynomials in $a$\\
$v \leftarrow 1 +$ number of equations in $I$\\
$x_v \leftarrow lhs(I_{v-1})$\\
$\alpha_v \leftarrow rhs(I_{v-1})$\\
*if* $v > 1$ *then* \{
\begin{addmargin}{1em} %2
-- 2.1 Multivariate case\\
$A \leftarrow product(a_i,i=1,...,r)$\\
*for* $j$ *from* 1 *to* $r$ *do* \{
$b_j \leftarrow \frac{A}{a_j}$ \}\\
$anew \leftarrow$ substitute$(x_v=\alpha_v,a)$\\
$cnew \leftarrow$ substitute$(x_v=\alpha_v,c)$\\
$Inew \leftarrow$ updated list $i$ with $x_v=\alpha_v$ deleted\\
$\sigma \leftarrow$ MultivariateDiophant$(anew,cnew,Inew,d,p,k)$\\
$e \leftarrow (c-sum(\sigma_i b_i, i=1,...,r)) mod p^k$\\
$monomial \leftarrow 1$\\
*for* $m$ *from* 1 *to* $d$ *while* $e \ne 0$ *do* \{\\ 
\begin{addmargin}{1em} %3
$monomial \leftarrow monomial \times (x_v-\alpha_v)$\\
$cm \leftarrow$ coeff of $(x_v-\alpha_v)^m$ in the Taylor expansion of $e$
about $x_v=\alpha_v$\\
*if* $cm \ne 0$ *then* \{
\begin{addmargin}{1em} %4
$\Delta s \leftarrow$ MultivariateDiophant$(anew,cm,Inew,d,p,k)$\\
$\Delta s \leftarrow \Delta s\times monomial$ -- element-by-element operation\\
$\sigma \leftarrow \sigma + \Delta s$ -- element-by-element operation\\
$e \leftarrow (e-sum(\Delta s_i b_i,i=1,...,r))
 mod p^k$ \} \} \}
\end{addmargin} %4
\end{addmargin} %3
*else* \{
\begin{addmargin}{1em} %5
-- 2.2 Univariate case\\
$x_1 \leftarrow$ the variable appearing in $a$\\
-- Method: For each power of $x_1$, call UnivariateDiophant\\
$\sigma \leftarrow$ zero list of length $r$\\
*for* each term $z$ in $c$ *do* \{
\begin{addmargin}{1em} %6
$m \leftarrow degree(z,x_1)$\\
$cm \leftarrow lcoeff(z)$\\
$\Delta s \leftarrow$ UnivariateDiophant$(a,x_1,m,p,k)$\\
$\Delta s \leftarrow \Delta s \times cm$ -- element-by-element operations\\
$\sigma \leftarrow \sigma + \Delta s$ -- element-by-element-operations \} \}
\end{addmargin} %6
\end{addmargin} %5
\end{addmargin} %2
*return*($\sigma$ mod $p^k$)
\end{addmargin} %1
*end*

[cite:@Gedd92] p 270\\
*procedure* UnivariateDiophant$(a,x,m,p,k)$\\
\begin{addmargin}{1em}
-- Solve in $*Z*_{p^k}[x]$ the univariate polynomial diophantine equation\\
-- $\sigma_1\times b_1+\cdots +\sigma_r\times b_r 
\equiv x^m ( mod  p^k)$\\
-- where, in terms of the given list of polynomials $a_1,...,a_r$\\
-- the polynomials $b_i,i=1,...,r$, are defined by\\
-- $b_i=a_i\times\cdots\times a_{i-1}
\times a_{i+1}\times\cdots\times a_r$\\
-- The unique solution $\sigma_1,...,\sigma_r$ will be computed such that\\
-- $deg(\sigma_i) < deg(a_i)$\\
--\\
-- Conditions: $p$ must not divide lcoeff($a_i$), $i=1,...,r$\\
-- $a_i mod p,i=1,...,r$, must be pairwise relatively
prime in $*Z*_p[x]$\\
--\\
-- OUTPUT\\
-- The value returned is the list $\sigma = [\sigma_1,...,\sigma_r]$

$r \leftarrow$ number of polynomials in $a$\\
*if* $r > 2$ *then* \{
\begin{addmargin}{1em} %2
$s \leftarrow$ MultiTermEEAlift$(a,p,k)$\\
$result \leftarrow []$\\
*for* $j$ *from* 1 to $r$ *do* \{
\begin{addmargin}{1em} %3
$result \leftarrow append(result,
rem(x^ms_j,a_j) mod p^k)$ \} \}
\end{addmargin} %3
\end{addmargin} %2
*else* \{
\begin{addmargin}{1em} %4
$s \leftarrow EEAlift(a_2,a_1,p,k)$\\
$q \leftarrow quo(x^ms_1,a_1) mod p^k$\\
$result \leftarrow [rem(x^ms_1,a_1) mod p^k,
(x^ms_2 + q a_2) mod p^k]$ \}
\end{addmargin} %4
*return*(/result/)
\end{addmargin} %1
*end*

[cite:@Gedd92] p 270-271\\
*procedure* MultiTermEEAlift$(a,p,x)$\\
\begin{addmargin}{1em} %1
-- MultiTermEEAlift computes $s_1,...,s_r$ such that\\
-- $s_1\times b_1+\cdots+s_r\times b_r \equiv 1 (mod p^k)$\\
-- with $deg(s_j) < deg(a_j)$ where, in terms of the 
given list of\\
-- polynomials $a_1,...,a_r$, the polynomials $b_i$ are defined by:\\
-- $b_i=a_1\times\cdots\times a_{i-1}\times a_{i+1}\times\cdots
\times a_r, i=1,...,r$\\
--\\
-- Conditions: $p$ must not divide $lcoeff(a_i),i=1,...,r$\\
-- $a_i$ mod $p,i=1,...,r$, must be pairwise relatively prime in
$*Z*_p[x]$\\
$r \leftarrow$ number of polynomials in $a$\\
$q_{r-1} \leftarrow a_r$\\
*for* $j$ *from* $r-2$ *by* -1 *to* 1 *do* \{\\
\begin{addmargin}{1em} %2
$q_j \leftarrow a_{j+1}\times q_{j+1}$ \}
\end{addmargin} %2
$\beta_0 \leftarrow 1$\\
*for* $j$ *from* 1 *to* $r-1$ *do* \{
\begin{addmargin}{1em} %3
$\sigma \leftarrow 
MultivariateDiophant([q_j,a_j],\beta_{j-1},0,p,k)$\\
$\beta_j \leftarrow \sigma_1$\\
$s_j \leftarrow \sigma_2$ \}\\
\end{addmargin} %3
$s_r \leftarrow \beta_{r-1}$\\
*return*($[s_1,...,s_r]$)
\end{addmargin} %1
*end*

[cite:@Gedd92] p 271\\
*procedure* EEAlift$(a,b,p,k)$\\
\begin{addmargin}{1em}
-- EEAlift computes $s,t$ such that $s a + t b \equiv 1 (mod p^k)$\\
-- with $deg(s) < deg(b)$ and
$deg(t) < deg(a)$\\
-- Assumption: GCD($a$ mod $p$, $b$ mod $p) = 1$ in $*Z*_p[x]$\\
$x \leftarrow $ the variable appearing in $a$ and $b$\\
$amodp \leftarrow a  mod p$\\
$bmodp \leftarrow b  mod p$\\
$s,t \leftarrow $ polynomials in $*Z*_p[x]$ computing by the
Extended Euclidean Algorithm such that\\
\hspace*{1cm} $s\ amodp + t\ bmodp \equiv 1 (mod p)$\\
$smodp \leftarrow s$\\
$tmodp \leftarrow t$\\
$modulus \leftarrow p$\\
*for* $j$ *from* 1 *to* $k-1$ *do* \{
\begin{addmargin}{1em}
$e \leftarrow 1-s\times a-t\times b$\\
$c \leftarrow \frac{e}{modulus}  mod p$\\
$\overline{\sigma} \leftarrow smodp\times c$\\
$\overline{\tau} \leftarrow tmodp\times c$\\
$q \leftarrow quo(\overline{\sigma},bmodp) mod p$\\
$\sigma \leftarrow rem(\overline{\sigma},bmodp) mod p$\\
$\tau \leftarrow (\overline{\tau}+q\times amodp) mod p$\\
$s \leftarrow s + \sigma\times modulus$\\
$t \leftarrow t + \tau\times modulus$\\
$modulus \leftarrow modulus\times p$ \}
\end{addmargin}
*return*($[s,t]$)
\end{addmargin}
*end*

*** Background

*** Example

* Multivariate Hensel Lifting
[cite:@Gedd92] p 272\\
*procedure* MultivariateHensel$(a,I,p,l,u,lcU)$
\begin{addmargin}{1em} %1
-- INPUT\\
-- (1) A multivariate polynomial 
$a(x_1,...,a_v) \in *Z*[x_1,...,x_v]$\\
-- which is primitive as a polynomial in the special variable $x_1$\\
-- (2) I, a list of equations 
$[x_2=\alpha_2,x_3=\alpha_3,...,x_v=\alpha_v]$\\
-- representing the evaluation homomorphism used; mathematically,\\
-- we view it as the ideal 
I$=<x_2-\alpha_2,x_3-\alpha_3,...,x_v-\alpha_v>$\\
-- and the following conditions must hold: 
lcoeff($a,x_1)\ne 0 (mod I)$\\
-- (3) A prime integer $p$ which does not divide lcoeff($a$ mod I)\\
-- (4) A positive integer $l$ such that $p^l/2$ bounds the magnitude of all\\
-- integers appearing in $a$ and in any of its factors to be computed\\
-- (5) A list $u$ of $n>1$ univariate polynomials in $*Z*_{p^l}[x_1]$
which are\\
-- pairwise relatively prime in the Euclidean domain $*Z*_p[x_1]$,\\
-- such that 
$a \equiv u_1\times u_2\times\cdots\times u_n (mod <I,p^l>)$\\
-- (6) a list $lcU$ of the $n$ correct multivariate leading coefficients\\
-- corresponding to the univariate factors $u$\\
--\\
-- OUTPUT\\
-- (1) If there exist $n$ polynomials 
$U_1,U_2,...,U_n \in *Z*[x_1,...,x_v]$\\
-- such that $a=U_1\times U_2\times\cdots\times U_n$ and for each 
$i=1,2,...,n$\\
-- $U_i/lcoeff(U_i,x_1)\equiv u_i/lcoeff(u_i,x_i)
( mod <I,p^l>)$\\
-- (where the divisions here are in the ring of integers mod $p^l$)\\
-- then the list $U=\{U_1,U_2,...,U_n\}$ will be the value returned\\
-- (2) Otherwise, the value returned will signal "no such factorization"\\
--\\
-- Remark: The mod operation must use the symmetric representation\\
--\\
-- 1. Initialization for the multivariate iteration\\
$v \leftarrow 1+$ number of equations in $I$\\
$A_v \leftarrow a$\\
*for* $j$ *from* $v$ *by* -1 *to* 2 *do* \{
\begin{addmargin}{1em} %2
$x_j \leftarrow lhs(I_{j-1})$\\
$\alpha_j \leftarrow rhs(I_{j-1})$\\
$A_{j-1} \leftarrow 
substitute(x_j=\alpha_j,A_j) mod p^l$ \}
\end{addmargin} %2
$maxdeg \leftarrow max(degree(a,x_i),i=2,...,v)$\\
$U \leftarrow u$\\
$n \leftarrow$ number of polynomials in $u$\\
-- 2. Variable-by-variable Hensel iteration\\
*for* $j$ *from* 2 *to* $v$ *do* \{
\begin{addmargin}{1em} %3
$U1 \leftarrow U$\\
$monomial \leftarrow 1$\\
*for* $m$ *from* 1 *to* $n$ *do* \{
\begin{addmargin}{1em} %4
*if* $lcU_m \ne 1$ *then* \{
\begin{addmargin}{1em} %5
$coef \leftarrow substitute(\{I[j],...,I[v-1]\},lcU_m)
 mod p^l$\\
$U \leftarrow$ updated list $U$ with 
lcoeff($U_m,x_1$) replaced by $coef$ \} \}
\end{addmargin} %5
\end{addmargin} %4
$e \leftarrow A_j-product(U_i,i=1,...,n)$\\
*for* $k$ *from* 1 *to* degree($A_j,x_j$) 
*while* $e\ne 0$ *do* \{
\begin{addmargin}{1em} %6
$monomial \leftarrow monomial\times (x_j-\alpha_j)$\\
$c \leftarrow$ coeff of $(x_j-\alpha_j)^k$ in the Taylor expansion
of $e$ about $x_j=\alpha_j$\\
*if* $c\ne 0$ *then* \{
\begin{addmargin}{1em} %7
$\Delta U \leftarrow 
MultivariateDiophant(U1,c,[I[1],...,I[j-2]],maxdeg,p,l)$\\
$\Delta U \leftarrow \Delta U\times monomial$ 
-- element-by-element operations\\
$U \leftarrow (U + \Delta U)  mod p^l$
-- element-by-element operations\\
$e \leftarrow (A_j-product(U_i,i=1,...,n)) mod p^l$
\} \} \}
\end{addmargin} %7
\end{addmargin} %6
\end{addmargin} %3
-- 3. Check termination status\\
*if* $a=product(U_i,i=1,...,n)$ *then return*($U$)
\begin{addmargin}{1em} %8
*else return*(/no such factorization exists/)
\end{addmargin} %8
\end{addmargin} %1
*end*

*** Background

*** Example

* Modular GCD
[cite:@Gedd92] p 307\\
*procedure* MGCD(A,B)\\
\begin{addmargin}{1em}
-- Given $A,B \in *Z*[x_1,...,x_k]$, nonzero, we determine the
GCD of the\\
-- two polynomials via modular reduction.\\
-- Remove integer content\\
$a \leftarrow icont(A)$\\
$b \leftarrow icont(B)$\\
$A \leftarrow A/a$\\
$B \leftarrow B/b$\\
-- Compute coefficient bound for GCD(A,B)\\
$c \leftarrow igcd(a,b)$\\
$g \leftarrow igcd(lcoeff(A),lcoeff(B))$\\
$(q,H) \leftarrow (0,0)$\\
$n \leftarrow min(deg_k(A),deg_k(B))$\\
$limit \leftarrow 2^n\cdot |g|\cdot min(||A||_\infty,||B||_\infty)$\\
*while* true *do* \{
\begin{addmargin}{1em} %2
$p \leftarrow New(LargePrime)$\\
*while* $p|q$ *do* $p \leftarrow New(LargePrime)$\\
$A_p \leftarrow A  mod p$\\
$B_p \leftarrow B  mod p$\\
$g_p \leftarrow  mod p$\\
$C_p \leftarrow PGCD(A_p,B_p,p)$\\
$m \leftarrow deg_k(C_p)$\\
-- Normalize so that $g_p = lcoeff(C_p)$\\
$C_p \leftarrow g_p\cdot lcoeff(C_p)^{-1}\cdot C_p$\\
-- Test for unlucky homomorphisms\\
*if* $m < n$ *then* \{
\begin{addmargin}{1em} %3
$(q,H) \leftarrow (p,C_p)$\\
$n \leftarrow m$ \}
\end{addmargin} %3
*elseif* $m=n$ *then* \{
\begin{addmargin}{1em} %4
-- Test for completion. Update coefficients of\\
-- GCD candidate H and modulus $q$ via integer CRA\\
*for all* coefficients $h_i$ in $H$ *do* \{
\begin{addmargin}{1em} %5
$h_i \leftarrow IntegerCRA([q,p],[h_i,(C_p)_i])$\\
$q \leftarrow q\cdot p$ \}
\end{addmargin} %5
\end{addmargin} %4
*if* $q > limit$ *then* \{
\begin{addmargin}{1em} %6
-- Remove integer content of result and do division check\\
$C \leftarrow pp(H)$\\
*if* $C|A$ *and* $C|B$ *then*
\begin{addmargin}{1em} %7
*return*($c\cdot C$) \}
\end{addmargin} %7
\end{addmargin} %6
*elseif* $m=0$ *then*
\begin{addmargin}{1em} %8
*return*($c$) \}
\end{addmargin} %8
\end{addmargin} %2
\end{addmargin}
*end*

*** Background

*** Example

* Multivariate GCD Reduction
[cite:@Gedd92] p 309\\
*procedure* PGCD$(A,B,p)$
\begin{addmargin}{1em}
-- Given $A,B \in *Z*_p[x_1,...,x_k]$\\
-- PGCD$(A,B,p)$ calculates the GCD of $A$ and $B$\\
*if* $k=1$ *then* \{ -- Call univariate GCD algorithm
\begin{addmargin}{1em} %2
$C \leftarrow UGCD(A,B,p)$\\
*if* deg$(C)=0$ *then* $C \leftarrow 1$\\
*return*$(C)$ \}
\end{addmargin} %2
-- Determine content of $A$ and $B$ considered as multivariate\\
-- polynomials in $*Z*_p[x_1,...,x_{k-1}]$ with coefficients from
$*Z*_p[x_k]$\\
$a \leftarrow cont(A)$\\
$b \leftarrow cont(B)$\\
$A \leftarrow A/a$\\
$B \leftarrow B/b$\\
$c \leftarrow UGCD(a,b,p)$\\
$g \leftarrow UGCD(lcoeff(A),lcoeff(B),p)$\\
-- Notice that both $c$ and $g$ are in $*Z*_p[x_k]$\\
-- Main loop\\
$(q,H) \leftarrow (1,1)$\\
$n \leftarrow min(deg_k(A),deg_k(B))$\\
$limit \leftarrow n + deg_k(g)$\\
*while* true *do* \{
\begin{addmargin}{1em} %3
$b \leftarrow New(Member *Z*_p)$ with $g(b) \ne 0$\\
$A_b \leftarrow A mod (x_k-b)$\\
$B_b \leftarrow B mod (x_k-b)$\\
$C_b \leftarrow PGCD(A_b,B_b,p)$\\
$m \leftarrow deg_{k-1}(C_b)$\\
$g_b \leftarrow g(b)$\\
-- Normalize $C_b$ so that lcoeff$(C_b)=g_b$\\
$C_b \leftarrow g_b\cdot lcoeff(C_b)^{-1}C_b$\\
-- Test for unlucky homomorphism\\
*if* $m<n$ *then* \{
\begin{addmargin}{1em} %4
$(q,H) \leftarrow (1,1)$\\
$n \leftarrow m$ \}
\end{addmargin} %4
*elseif* $m=n$ *then*
\begin{addmargin}{1em} %5
-- Use previous result to continue building $H$ via\\
-- polynomial interpolation (i.e. via polynomial CRA)\\
$(q,H) \leftarrow PolyInterp(q,H,b,C_b,p)$
\end{addmargin} %5
--Test for completion\\
*if* $lcoeff(H)=g$ *then* \{
\begin{addmargin}{1em} %5
$C \leftarrow pp(H)$\\
*if* $C|A$ and $C|B$ *then return*$(c\cdot C)$\\
*elseif* $m=0$ *then return*$(c)$ \} \}
\end{addmargin} %5
\end{addmargin} %3
\end{addmargin}
*end*

*** Background

*** Example

* Extended Zassenhaus GCD
[cite:@Gedd92] p 316\\
*procedure* EX-GCD$(A,B)$
\begin{addmargin}{1em}
-- Given two polynomials $A,B \in *Z*[x,y_1,...,y_k]$\\
-- with $deg_x(A) \ge deg_x(B)$, we compute the triple\\
-- $<A/C,B/C,C>$ where $C=GCD(A,B)$, using Hensel lifting\\
-- Compute the content, primitive part, lcoeff, GCD, etc. all viewing $A$\\
-- and $B$ as polynomials over the coefficient domain 
$*Z*[y_1,...,y_k]$\\
$a \leftarrow cont(A)$\\
$b \leftarrow cont(B)$\\
$A \leftarrow A/a$\\
$B \leftarrow B/a$\\
$g \leftarrow GCD(a,b)$\\
$a \leftarrow a/g$\\
$b \leftarrow b/g$\\
-- Find a valid evaluation prime\\
$p \leftarrow New(Prime)$ with lcoeff($A$) mod $p\ne 0$ and
lcoeff($B$) mod $p\ne 0$\\
-- Find a valid evaluation point $*b*=(b_1,...,b_k)$\\
-- with $0 \le b_i < p$ and as many $b_i's=0$ as possible\\
$b \leftarrow New(EvaluationPoint)$ with lcoeff$(A)(*b*)\ne 0$
and lcoeff$(B)(*b*)\ne 0$\\
$A_I \leftarrow A(*b*)$ mod $p$\\
$B_I \leftarrow B(*b*)$ mod $p$\\
$C_I \leftarrow UGCD(A_I,B_I)$\\
$d \leftarrow deg_x(C_I)$\\
*if* $d=0$ *then return*$(<Aa,Bb,g>)$\\
-- Double check the answer: Choose a new prime and evaluation point\\
$p^\prime \leftarrow New(Prime)$ with lcoeff($A$) mod $p^\prime\ne 0$
and lcoeff($B$) mod $p^\prime\ne 0$\\
$*c* \leftarrow New(EvaluationPoint)$ with lcoeff($A)(*c*)$ mod $p^\prime\ne 0$ and lceoff($B)(*c*)\ne 0$\\
$A_{I^\prime} \leftarrow A(*c*)  mod p^\prime$\\
$B_{I^\prime} \leftarrow B(*c*)  mod p^\prime$\\
$C_{I^\prime} \leftarrow UGCD(A_{I^\prime},B_{I^\prime})$\\
$d_{I^\prime} \leftarrow deg_x(C_{I^\prime})$\\
*if* $d_{I^\prime} < d$ *then* \{
\begin{addmargin}{1em} %2
-- Previous evaluation was bad, try again\\
$A_I \leftarrow A_{I^\prime}$\\
$B_I \leftarrow B_{I^\prime}$\\
$C_I \leftarrow C_{I^\prime}$\\
$d \leftarrow d_{I^\prime}$\\
$*b* \leftarrow *c*$\\
*goto* double check step \}
\end{addmargin} %2
*elseif* $d_{I^\prime} > d$ *then* \{
\begin{addmargin}{1em} %3
-- This evaluation was bad; repeat double check step\\
*goto* double check step \}
\end{addmargin} %3
-- Test for special cases\\
*if* $d = 0$ *then return*$(<A\cdot a,B\cdot b,g>)$\\
*if* $d=deg_x(B)$ *then* \{
\begin{addmargin}{1em} %4
*if* $B|A$ *then return*$(<a\cdot A/B,b,B\cdot g>)$\\
*else* \{
\begin{addmargin}{1em} %5
-- Bad evaluation, repeat the double check\\
$d \leftarrow d-1$\\
*goto* double check step \} \}
\end{addmargin} %5
\end{addmargin} %4
-- Check for relatively prime cofactors\\
*if* UGCD$(B_I,C_I)=1$ *then* \{
\begin{addmargin}{1em} %6
$U_I \leftarrow B$\\
$H_I \leftarrow B_I/C_I$\\
$c \leftarrow b$ \}
\end{addmargin} %6
*elseif* UCGD$(A_I,C_I)=1$ *then* \{
\begin{addmargin}{1em} %7
$U_I \leftarrow A$\\
$H_I \leftarrow A_I/C_I$\\
$c \leftarrow a$ \}
\end{addmargin} %7
*else return*(SGCD$(A,B,*b*,p)$)\\
-- Lifting step\\
$U_I \leftarrow c\cdot U_I$\\
$c_I \leftarrow c(*b*) mod p$\\
$C_I \leftarrow c_I\cdot C_I$\\
$(C,E) \leftarrow EZ\_LIFT(U_I,C_I,H_I,*b*,p.c)$\\
*if* $U_I=C\cdot E$ *then goto* double check step\\
-- Final check\\
$C \leftarrow pp(C)$\\
*if* $C|B$ *and* $C|A$ *then return*
$(<a\cdot A/C,b\cdot B/C,g\cdot C>)$\\
*else goto* double check step
\end{addmargin}
*end*

*** Background

*** Example

* GCD Heuristic
[cite:@Gedd92] p 330\\
*procedure* GCDHEU$(A,B)$
\begin{addmargin}{1em} %1
-- Given polynomials $A,B \in *Z*[x_1,...,x_k]$ we use\\
-- a heuristic method for trying to determine $G=GCD(A,B)$\\
$vars \leftarrow$ Indeterminates($A$) $\cup$ Indeterminates($B$)\\
*if* $SizeOf(vars)=0$ *then return*$(igcd(A,B))$\\
*else* $x \leftarrow vars[1]$\\
$\xi \leftarrow 2\cdot min(||A||_\infty,||B||_\infty)+2$\\
*to* 6 *do* \{
\begin{addmargin}{1em} %2
*if* $length(\xi)\cdot max(deg_x(A),
deg_x(B))>5000$
*then*
\begin{addmargin}{1em} %3
Return\_To\_Top\_Level(fail\_flag)
\end{addmargin} %3
$\gamma \leftarrow GCDHUE(\phi_{x-\xi}(A),\phi_{x-\xi}(B))$\\
*if* $\gamma \ne fail\_flag$ *then*
\begin{addmargin}{1em} %4
-- Generate polynomial $G$ from $\xi$-adic expansion of $\gamma$\\
$G \leftarrow 0$\\
*for* $i$ *from* 0 *while* $\gamma \ne 0$ *do* \{
\begin{addmargin}{1em} %5
$g_i \leftarrow \phi_\xi{\gamma}$\\
$G \leftarrow G+g_i\cdot x^i$\\
$\gamma \leftarrow (\gamma-g_i)/\xi$ \}
\end{addmargin} %5
*if* $G|A$ *and* $G|B$ *then return*($G$)
\end{addmargin} %4
-- Create a new evaluation point using square of golden ratio\\
$\eta \leftarrow iquo(\xi\times 73794, 27011)$ \}
\end{addmargin} %2
*return*(fail\_flag)
\end{addmargin} %1
*end*

*** Background

*** Example

* Square-Free Factorization
[cite:@Gedd92] p 340\\
*procedure* SquareFree($a(x)$)
\begin{addmargin}{1em}
-- Given a primitive polynomial $a(x) \in *R*[x]$, *R* a UFD\\
-- with characteristic zero, we calculate the\\
-- square-free factorization of $a(x)$\\
$i \leftarrow 1$\\
Output $\leftarrow 1$\\
$b(x) \leftarrow a^\prime(x)$\\
$c(x) \leftarrow GCD(a(x),b(x))$\\
$w(x) \leftarrow a(x)/c(x)$\\
*while* $c(x) \ne 1$ *do* \{
\begin{addmargin}{1em}
$y(x) \leftarrow GCD(w(x),c(x))$\\
$z(x) \leftarrow w(x)/y(x)$\\
Output $\leftarrow$ Output$\cdot z(x)^i$\\
$i \leftarrow i+1$\\
$w(x) \leftarrow y(x)$\\
$c(x) \leftarrow c(x)/y(x)$ \}
\end{addmargin}
Output $\leftarrow$ Output$\cdot w(x)^i$\\
*return*(Output)
\end{addmargin}
*end*

*** Background

*** Example

* Yun's Square-Free Factorization
[cite:@Gedd92] p 342\\
*procedure* SquareFree2($a(x)$)
\begin{addmargin}{1em}
-- Given a primitive polynomial $a(x) \in *R*[x]$, *R* a\\
-- UFD of characteristic zero, we calculate the square-free\\
-- factorization of $a(x)$ using Yun's algorithm\\
$i \leftarrow 1$\\
Output $\leftarrow 1$\\
$b(x) \leftarrow a^\prime(x)$\\
$c(x) \leftarrow GCD(a(x),b(x))$\\
*if* $c(x)=1$ *then* $w(x) \leftarrow a(x)$\\
*else* \{
\begin{addmargin}{1em}
$w(x) \leftarrow a(x)/c(x)$\\
$y(x) \leftarrow b(x)/c(x)$\\
$z(x) \leftarrow y(x)-w^\prime(x)$\\
*while* $z(x) \ne 0$ *do* \{
\begin{addmargin}{1em}
$g(x) \leftarrow GCD(w(x),z(x))$\\
Output $\leftarrow$ Output$\cdot g(x)^i$\\
$i \leftarrow i+1$\\
$w(x) \leftarrow w(x)/g(x)$\\
$y(x) \leftarrow z(x)/g(x)$\\
$z(x) \leftarrow y(x)-w^\prime(x)$ \} \}
\end{addmargin}
\end{addmargin}
Output $\leftarrow$ Output$\cdot w(x)^i$\\
*return*(Output)
\end{addmargin}
*end*

*** Background

*** Example

* Finite Field Square-Free Factorization
[cite:@Gedd92] p 345\\
*procedure* SquareFreeFF$(a(x),q)$
\begin{addmargin}{1em}
-- Given a monic polynomial $a(x) \in GF(q)[x]$, with $GF(q)$ a\\
-- Galois field of order $q=p^m$, we calculate the\\
-- square-free factorization of $a(x)$\\
$i \leftarrow 1$\\
Output $\leftarrow 1$\\
$b(x) \leftarrow a^\prime(x)$\\
*if* $b(x) \ne 0$ *then* \{
\begin{addmargin}{1em}
$c(x) \leftarrow GCD(a(x),b(x))$\\
$w(x) \leftarrow a(x)/c(x)$\\
*while* $w(x) \ne 1$ *do* \{
\begin{addmargin}{1em}
$y(x) \leftarrow GCD(w(x),c(x))$\\
$z(x) \leftarrow w(x)/y(x)$\\
Output $\leftarrow$ Output$\cdot z(x)^i$\\
$i \leftarrow i+1$\\
$w(x) \leftarrow y(x)$\\
$c(x) \leftarrow c(x)/y(x)$ \}
\end{addmargin}
*if* $c(x) \ne 1$ *then* \{
\begin{addmargin}{1em}
$c(x) \leftarrow c(x)^{1/p}$\\
Output $\leftarrow$ Output$\cdot (SquareFreeFF(c(x)))^p$ \}\}
\end{addmargin}
\end{addmargin}
*else* \{
\begin{addmargin}{1em}
$a(x) \leftarrow a(x)^{1/p}$\\
Output $\leftarrow (SquareFreeFF(a(x)))^p$ \}
\end{addmargin}
*return*(Output)
\end{addmargin}
*end*

*** Background

*** Example

* Berlekamp's Factoring
[cite:@Gedd92] p 352\\
*procedure* Berlekamp$(a(x),q)$
\begin{addmargin}{1em}
-- Given a square-free polynomial $a(x) \in GF(q)[x]$\\
-- calculate irreducible factors $a_1(x),...,a_k(x)$ such\\
-- that $a(x)=a_1(x)\cdots a_k(x)$\\
$Q \leftarrow FormMatrixQ(a(x),q)$\\
$v^{[1]},v^{[2]},...,v^{[k]} \leftarrow NullSpaceBasis(Q-I))$\\
-- Note we can ensure that $v^{[1]}=(1,0,...,0)$\\
$factors \leftarrow \{a(x)\}$\\
$r \leftarrow 2$\\
*while* SizeOf$(factors) < k$ *do* \{
\begin{addmargin}{1em}
*foreach* $u(x) \in factors$ *do* \{
\begin{addmargin}{1em}
*foreach* $s \in GF(q)$ *do* \{
\begin{addmargin}{1em}
$g(x) \leftarrow GCD(v^{[r]}(x)-s,u(x))$\\
*if* $g(x) \ne 1$ *or* $g(x) \ne u(x)$ *then* \{
\begin{addmargin}{1em}
Remove$(u(x),factors)$\\
$u(x) \leftarrow u(x)/g(x)$\\
Add$(\{u(x),g(x)\},factors)$ \}
\end{addmargin}
*if* SizeOf$(factors) = k$ *then return*$(factors)$ \}
\end{addmargin}
\end{addmargin}
$r \leftarrow r+1$ \} \}
\end{addmargin}
\end{addmargin}
*end*

*** Background

*** Example

* Form Q Matrix
[cite:@Gedd92] p 353\\
*procedure* FormMatrixQ$(a(x),q)$
\begin{addmargin}{1em}
-- Given a polynomial $a(x)$ of degree $n$ in $GF(q)[x]$, calculate\\
-- the $Q$ matrix required by Berlekamp's algorithm\\
$n \leftarrow deg(a(x))$\\
$*r* \leftarrow (1,0,...,0)$\\
$Row(0,Q) \leftarrow *r*$\\
*for* $m$ *from* 1 *to* $(n-1)q$ *do* \{
\begin{addmargin}{1em}
$*r* \leftarrow (-r_{n-1}\cdot a_0,r_0-r_{n-1}\cdot a_1,...,
r_{n-2}-r_{n-1}\cdot a_{n-1})$\\
*if* $q|m$ *then*
\begin{addmargin}{1em}
Row$(m/q,Q) \leftarrow *r*$ \}
\end{addmargin}
\end{addmargin}
*return*($Q$)
\end{addmargin}
*end*

*** Background

*** Example

* Null Space Basis
[cite:@Gedd92] p 356\\
*procedure* NullSpaceBasis$(M)$
\begin{addmargin}{1em}
-- Given a square matrix $M$, we return a basis $\{v^{[1]},...,v^{[k]}\}$
for the null\\
-- space $\{ *v*:*v*\cdot M=*0*\}$ of $M$. 
This algorithm does this\\
-- by transforming $M$ to triangular idempotent form\\
$n \leftarrow rowsize(M)$\\
*for* $k$ *from* 1 *to* $n$ *do* \{
\begin{addmargin}{1em}
-- Search for pivot element\\
*for* $i$ *from* $k$ *to* $n$ *while* $M_{ki}=0$ *do*
$i \leftarrow i+1$\\
*if* $i \le n$ *then* \{
\begin{addmargin}{1em}
-- Normalize column $i$ and interchange this with column $k$\\
Column$(i,M) \leftarrow Column(i,M)\cdot M_{ki}^{-1}$\\
SwitchColumn$(i,k,M)$\\
-- Eliminate rest of row $k$ via column operations\\
*for* $i$ *to* $n$ *with* $i\ne k$ *do*
\begin{addmargin}{1em}
Column$(i,M) \leftarrow Column(i,M)-Column(k,M)\cdot M_{ki}$ \} \}
\end{addmargin}
\end{addmargin}
-- Convert $M$ to $M-I$\\
*for* $i$ *from* 1 *to* $n$ *do* $M_{ii} \leftarrow M_{ii}-1$\\
-- Read off nonzero rows of $M$\\
$i \leftarrow 0$\\
$j \leftarrow 1$\\
*while* $j \le n$ *do* \{
\begin{addmargin}{1em}
*while* Row$(j,M)=0$ *and* $j \le n$ *do* $j \leftarrow j+1$\\
*if* $j \le n$ *then* \{
\begin{addmargin}{1em}
$i \leftarrow i+1$\\
$v^{[i]} \leftarrow Row(j,M)$ \} \}
\end{addmargin}
\end{addmargin}
\end{addmargin}
*return*$(\{v^{[1]},...,v^{[i]}\})$
\end{addmargin}
*end*

*** Background

*** Example

* Big Prime Berlekamp Factoring
[cite:@Gedd92] p 367\\
*procedure* BigPrimeBerlekamp$(a(x),p^m)$
\begin{addmargin}{1em}
-- Given a square-free polynomial $a(x) \in GF(p^m)[x]$\\
-- calculate irreducible factors $a_1(x),...,a_k(x)$ such\\
-- that $a(x)=a_1(x)\cdots a_k(x)$ using the big prime\\
-- variation of Berlekamp's algorithm\\
$Q \leftarrow BinaryPoweringFormQ(a(x))$\\
$*v*^{[1]},*v*^{[2]},...,*v*^{[k]} 
\leftarrow NullSpaceBasis(Q-I)$\\
-- Note: we can ensure that $*v*^{[1]}=(1,0,...,0)$\\
$factors \leftarrow \{a(x)\}$\\
*while* SizeOf$(factors) < k$ *do* \{
\begin{addmargin}{1em}
*foreach* $u(x) \in factors$ *do* \{
\begin{addmargin}{1em}
$(c_1,...,c_k) \leftarrow RandomCoefficients(GF(p^m))$\\
$v(x) \leftarrow c_1v^{[1]}(x)+\cdots+c_kv^{[k]}(x)$\\
*if* $p=2$ *then*
\begin{addmargin}{1em}
$v(x) \leftarrow v(x)+v(x)^2+\cdots+v(x)^{2^{m-1}}$
\end{addmargin}
*else* $v(x) \leftarrow v(x)^{(p^m-1)/2}-1  mod u(x)$\\
$g(x) \leftarrow GCD(v(x),u(x))$\\
*if* $g(x)\ne 1$ *and* $g(x)\ne u(x)$ *then* \{
\begin{addmargin}{1em}
Remove$(u(x),factors)$\\
$u(x) \leftarrow u(x)/g(x)$\\
Add$(\{u(x),g(x)\},factors)$\\
*if* SizeOf$(factors) = k$ *then return*$(factors)$ \} \} \}
\end{addmargin}
\end{addmargin}
\end{addmargin}
\end{addmargin}
*end*

*** Background

*** Example

* Partial Distinct Degree Factorization
[cite:@Gedd92] p 371\\
*procedure* PartialFactorDD$(a(x),q)$
\begin{addmargin}{1em}
-- Given a square-free polynomial $a(x)$ in $GF(q)[x]$\\
-- we calculate the partial distinct degree factorization\\
-- $a_1(x)\cdots a_d(x)$ of $a(x)$\\
$i \leftarrow 1$\\
$w(x) \leftarrow x$\\
$a_0(x) \leftarrow 1$\\
*while* $i \le degree(a(x))/2$ *do* \{
\begin{addmargin}{1em}
$w(x) \leftarrow w(x)^q mod a(x)$\\
$a_i(x) \leftarrow GCD(a(x),w(x)-x)$\\
*if* $a_i(x) \ne 1$ *then* \{
\begin{addmargin}{1em}
$a(x) \leftarrow a(x)/a_i(x)$\\
$w(x) \leftarrow w(x) mod a(x)$ \}
\end{addmargin}
$i \leftarrow i+1$ \}
\end{addmargin}
*return*$(a_0(x)\cdots a_{i-1}(x)a(x))$
\end{addmargin}
*end*

*** Background

*** Example

* Splitting Distinct Degree Factorization
[cite:@Gedd92] p 373\\
*procedure* SplitDD$(a(x),n,p^m)$
\begin{addmargin}{1em}
-- We assume that $a(x)$ is a polynomial in $GF(p^m)$\\
-- made up of factors all of degree $n$. We split $a(x)$\\
-- into its complete factorization via Cantor-Zassenhaus method\\
*if* deg$(a,x) \le n$ *then return*$(\{a(x)\})$\\
-- each factor has degree given by:\\
$m \leftarrow deg(a(x),x)/n$\\
$factors \leftarrow \{a(x)\}$\\
*while* SizeOf$(factors) < m$ *do* \{
\begin{addmargin}{1em}
$v(x) \leftarrow RandomPoly(degree=2n-1)$\\
*if* $p=2$ *then*
\begin{addmargin}{1em}
$v(x) \leftarrow v(x)+v(x)^2+\cdots+v(x)^{2^{n\cdot m-1}}$
\end{addmargin}
*else*
\begin{addmargin}{1em}
$v(x) \leftarrow v(x)^{(q^n-1)/2}-1$
\end{addmargin}
$g(x) \leftarrow GCD(a(x),v(x))$\\
*if* $g(x) \ne 1$ *and* $g(x) \ne a(x)$ *then*\\
$factors \leftarrow SplitDD(g(x),n,p^m) \cup 
SplitDD(a(x)/g(x),n,p^m)$ \}
\end{addmargin}
*return*($factors$)
\end{addmargin}
*end*

*** Background

*** Example

* Factorization over Algebraic Number Fields
[cite:@Gedd92] p 383\\
*procedure* AlgebraicFactorization$(a(z),m(x),\alpha)$
\begin{addmargin}{1em}
-- Given a square-free polynomial $a(z) \in F(\alpha)[z]$, $\alpha$\\
-- an algebraic number with minimal polynomial $m(x)$\\
-- of degree $n$, we factor $a$. We consider $a$ as\\
-- a bivariate polynomial in $\alpha$ and $z$.\\
--\\
-- Find $s$ such that Norm$(a_s(z))$ is square-free\\
$s \leftarrow 0$\\
$a_s(\alpha,z) \leftarrow a(\alpha,z)$\\
Norm$(a_s) \leftarrow res_x(m(x),a_x(x,z))$\\
*while* deg(GCD(Norm$(a_s)$,Norm$(a_s)^\prime))\ne 0$ *do* \{
\begin{addmargin}{1em}
$s\leftarrow s+1$\\
$a_s(\alpha,z) \leftarrow a_s(\alpha,z-\alpha)$\\
Norm$(a_s) \leftarrow res_x(m(x),a_s(x,z))$ \}
\end{addmargin}
-- Factor Norm$(a_s)$ in $F[z]$ and lift resutls to $F(\alpha)[z]$\\
$b \leftarrow$ factors(Norm$(a_s)$)\\
*if* SizeOf$(b)=1$ *then return*$(a(z))$\\
*else*
\begin{addmargin}{1em}
*foreach* $a_i(z) \in b$ *do* \{
\begin{addmargin}{1em}
$a_i(\alpha,z) \leftarrow GCD(a_i(z),a_s(\alpha,z))$\\
$a_i(\alpha,z) \leftarrow a_i(\alpha,z+s\cdot\alpha)$\\
substitute$(a_i(x) \leftarrow a_i(\alpha,z),b)$ \}
\end{addmargin}
\end{addmargin}
*return*$(b)$
\end{addmargin}
*end*

*** Background

*** Example

* Fraction-Free Gaussian Elimination
[cite:@Gedd92] p 398\\
*procedure* FractionFreeElim$(A)$
\begin{addmargin}{1em}
-- Given an $m\times m$ matrix $A$ (with entries $a_{ij}$),\\
-- reduce it to upper echelon form \\
$sign \leftarrow 1$\\
$divisor \leftarrow 1$\\
$r \leftarrow 1$\\
-- Eliminate below row $r$, with pivot in column $k$\\
*for* $k$ *from* 1 *to* $n$ *while* $r \le m$ *do* \{
\begin{addmargin}{1em}
-- Find a nonzero pivot\\
*for* $p$ *from* $r$ *to* $m$ 
*while* $a_{pk}=0$ *do* \{\}\\
*if* $p \le m$ *then* \{
\begin{addmargin}{1em}
-- Pivot is in row $p$, so switch rows $p$ and $r$\\
*for* $j$ *from* $k$ *to* $n$ *do* 
\{ interchange $a_{pj}$ and $a_{rj}$ \}\\
-- Keep track of sign changes due to row exchange\\
*if* $r\ne p$ *then* $sign \leftarrow -sign$\\
*for* $i$ *from* $r+1$ *to* $m$ *do* \{
\begin{addmargin}{1em} 
*for* $j$ *from* $k+1$ *to* $n$ *do* \{
\begin{addmargin}{1em} 
$a_{ij} \leftarrow (a_{rk}a_{ij}-a_{rj}a_{ik})/divisor$ \}
\end{addmargin}
$a_{ik} \leftarrow 0$ \}
\end{addmargin}
$divisor \leftarrow a_{rk}$\\
$r \leftarrow r+1$ \} \}
\end{addmargin}
\end{addmargin}
-- Optionally, compute the determinant for square\\
-- or augmented matrices\\
*if* $r=m+1$ *then* $det \leftarrow sign\cdot divisor$
*else* $det \leftarrow 0$\\
*return*$(A)$
\end{addmargin}
*end*

*** Background

*** Example

* Nonlinear Elimination
[cite:@Gedd92] p 417\\
*procedure* NonlinearElim$(P)$
\begin{addmargin}{1em}
-- Given a set of polynomials \\
-- $P=\{p_1,...,p_k\} \subset \tilde{F}[x_1,...,x_r]$\\
-- none of which are constants or multiples of any others, construct\\
-- a reduced system if possible.\\
-- Note that we always remove the (multivariate) content,\\
-- cecause of exponential coefficient growth\\
--\\
-- Distribute the $p_i$ into subsets (by domains); also note\\
-- all pairs of (distinct) polnomials in each subset\\
*for* $i$ *from* 1 *to* $r$ *do* \{
$E_i \leftarrow \emptyset; B_i \leftarrow \emptyset \}$\\
$E_{r+1} \leftarrow \emptyset$\\
*foreach* $p \in P$ *do* \{
\begin{addmargin}{1em}
*if* $p\in\tilde{F}[x_j,...,x_r]-\tilde{F}[x_{j+1},...,x_r]$
*then* \{
\begin{addmargin}{1em}
$B_j \leftarrow B_j \cup \{ [q,pp(p)]:q \in E_j \}$\\
$E_j \leftarrow E_j \cup \{ pp(p) \} \} \}$
\end{addmargin}
\end{addmargin}
-- Compute resultants until each $E_i$ has a member, or\\
-- no more resultants are left\\
*do until* $(E_i\ne\emptyset, 1 \le i\le r)$ 
*or* $(B_i = \emptyset, 1 \le i \le r-1)$ \{
\begin{addmargin}{1em}
$k \leftarrow max \{ i: B_i \ne \emptyset \}$\\
$[f,g] \leftarrow$ an element of $B_k$\\
$B_k \leftarrow B_k- \{ [f,g] \}$\\
$p \leftarrow pp(res_k(f,g))$\\
*if* $p \ne 0$ *then* \{
\begin{addmargin}{1em}
*if* $p=1$ *then return*($no solutions$)\\
*else if* 
$p \in \tilde{F}[x_j,...,x_r]-\tilde{F}[x_{j+1},...,x_r]$ *and*\\
\begin{addmargin}{1em}
(no $s \in E_j$ divides $p$) *then* \{
\end{addmargin}
$B_j\leftarrow B_j\cup\{[s,p]:s\in E_j\}$\\
$E_j\leftarrow E_j\cup \{p\}\}\}\}$
\end{addmargin}
\end{addmargin}
*return*$(\{E_1,...,E_r\})$
\end{addmargin}
*end*

*** Background

*** Example

* Solution of a Nonlinear System of Equations
[cite:@Gedd92] p 421\\
*procedure* NonlinearSolve$(P)$
\begin{addmargin}{1em}
-- Given a set $P \subset \tilde{F}[x_1,...,x_r]$ corresponding to a\\
-- system of $k$ nonlinear equations $(k\ge r)$ with finitely\\
-- many solutions, find the common roots of $P$\\
$G \leftarrow NonlinearElim(P)$\\
$roots \leftarrow \emptyset$\\
-- If we obtain a nonzero constant, there are no solutions\\
*if* no solutions exist *then return*$(roots)$\\
*else* \{
\begin{addmargin}{1em}
-- The reduced system $G$ has the form $\{E_1,...,E_r\}$\\
-- Find the roots of the univariate polynomials\\
$q \leftarrow$ GCD( polynomials in $E_r$)\\
$roots \leftarrow roots \cup \{ (\alpha):q(\alpha)=0 \}$\\
-- Now extend each partial root by back-solving\\
*for* $j$ *from* $r-1$ *by* -1 *to* 1 *do* \{
\begin{addmargin}{1em}
$R \leftarrow \emptyset$\\
*foreach* $(\alpha_{j+1},...,\alpha_r)\in roots$ *do* \{
\begin{addmargin}{1em}
$U_j \leftarrow \{e(x_j,\alpha_{j+1},...,\alpha_r):e \in E_j\}-\{0\}$\\
$q \leftarrow$ GCD( polynomials in $U_j$)\\
-- Note that $q$ may sometimes be constant\\
$R \leftarrow R \cup \{(\alpha,\alpha_{j+1},...,\alpha_r):q(\alpha)=0\}$\\
\end{addmargin}
\end{addmargin}
$roots \leftarrow R$ \}
\end{addmargin}
*return*$(roots)$
\end{addmargin}
*end*

*** Background

*** Example

* Full Reduction
[cite:@Gedd92] p 436\\
*procedure* Reduce$(p,Q)$
\begin{addmargin}{1em}
-- Given a polynomial $p$ and a set of polynomials $Q$\\
-- from the ring $F[x]$, find a $q$ such that $p \mapsto^* q$\\
-- Start with the whole polynomial\\
$r \leftarrow p$\\
$q \leftarrow 0$\\
-- If no reducers exist, strip off the leading monomial\\
-- otherwise, continue to reduce\\
*while* $r\ne 0$ *do* \{
\begin{addmargin}{1em}
*while* $R_{r,Q} \ne \emptyset$ *do* \{
\begin{addmargin}{1em}
$f \leftarrow selectpoly(R_{r,Q})$\\
$r \leftarrow r-\frac{M(r)f}{M(f)}$ \}
\end{addmargin}
$q \leftarrow q+M(r)$\\
$r \leftarrow r-M(r)$ \}
\end{addmargin}
*return*$(q)$
\end{addmargin}
*end*

*** Background

*** Example

* Buchberger's Algorithm for Gr\"obner Bases
[cite:@Gedd92] p 446\\
*procedure* Gbasis$(P)$
\begin{addmargin}{1em}
-- Given a set of polynomials $P$, compute $G$ such\\
-- that $<G>=<P>$ and $G$ is a Gr\"obner Basis\\
$G \leftarrow P$\\
$k \leftarrow length(G)$\\
-- We denote the $i$-th element of the ordered set $G$ by $G_i$\\
$B \leftarrow \{ [i,j]:1 \le i < j \le k \}$\\
*while* $B \ne \emptyset$ *do* \{
\begin{addmargin}{1em}
$[i,j] \leftarrow selectpair(B,G)$\\
$B \leftarrow B - \{[i,j]\}$\\
$h \leftarrow Reduce(Spoly(G_i,G_j),G)$\\
*if* $h\ne 0$ *then* \{
\begin{addmargin}{1em}
$G \leftarrow G \cup \{h\}$\\
$k \leftarrow k+1$\\
$B \leftarrow B \cup \{[i,k]:1\le i < k\} \}\}$
\end{addmargin}
\end{addmargin}
*return*$(G)$
\end{addmargin}
*end*

*** Background

*** Example

* Consruction of a Reduced Ideal Basis
[cite:@Gedd92] p 448\\
*procedure* ReduceSet$(E)$
\begin{addmargin}{1em}
-- Given a set $E$ (not necessarily a Gr\"obner basis),\\
-- compute $(\tilde{E})$ such that 
$<E>=<\tilde{E}>$ and $\tilde{E}$ is reduced\\
-- First, remove any redundant elements\\
$R \leftarrow E$\\
$P \leftarrow \emptyset$\\
$h \leftarrow Reduce(h,P)$\\
*while* $R \ne \emptyset$ *do* \{
\begin{addmargin}{1em}
$h \leftarrow selectpoly(R)$\\
$R \leftarrow R-\{h\}$\\
*if* $h \ne 0$ *then* \{
\begin{addmargin}{1em}
$Q \leftarrow \{q\in P$ such that hterm$(h)$ $|$ hterm$(q)$ \}\\
$R \leftarrow R \cup Q$\\
$P \leftarrow P - Q \cup \{h\}$ \}\}
\end{addmargin}
\end{addmargin}
-- Ensure each element is reduced modulo the others\\
$(\tilde{E}) \leftarrow \emptyset$\\
$S \leftarrow P$\\
*foreach* $h \in P$ *do* \{
\begin{addmargin}{1em}
$h \leftarrow Reduce(h,S-\{h\})$\\
$\tilde{E} \leftarrow \tilde{E} \cup \{h\}$ \}
\end{addmargin}
*return*$(\tilde{E})$
\end{addmargin}
*end*

*** Background

*** Example

* Improved Construction of Reduced Gr\"obner Basis
[cite:@Gedd92] p 450\\
*procedure* Gbasis$(P)$
\begin{addmargin}{1em}
-- Given polynomials $P$, find the corresponding reduced\\
-- Gr\"obner basis $G$\\
-- First, pre-reduce the raw input set\\
-- optionally, just set $G \leftarrow P$\\
$G \leftarrow ReduceSet(P)$\\
$k \leftarrow length(G)$\\
$B \leftarrow \{ [i,j] : 1\le i < j\le k \}$\\
*while* $B \ne \emptyset$ *do* \{
\begin{addmargin}{1em}
$[i,j] \leftarrow selectpair(B,G)$\\
$B \leftarrow B - \{[i,j]\}$\\
*if* criterion1$([i,j],G)$ *and* 
criterion2$([i,j],B,G)$ *then* \{
\begin{addmargin}{1em}
$h \leftarrow Reduce(Spoly(G_i,G_j),G)$\\
*if* $h \ne 0$ *then* \{
\begin{addmargin}{1em}
$G \leftarrow G \cup \{h\}$\\
$k \leftarrow k+1$\\
$B \leftarrow B \cup \{[i,k] : 1\le i < k\} \}\}\}$
\end{addmargin}
\end{addmargin}
\end{addmargin}
-- Discard redundant elements and inter-reduce\\
$R \leftarrow \{ g\in G  such that  R_{g,G}-\{g\}\ne \emptyset\}$\\
*return*(ReduceSet($G-R)$)
\end{addmargin}
*end*

*** Background

*** Example

* Solution of Systems for One Variable
[cite:@Gedd92] p 457\\
*procedure* Solve1$(P,\tilde{x})$
\begin{addmargin}{1em}
-- Given a system $P$ with finitely many solutions, find\\
-- the smallest polynomial containing the solutions in $\tilde{x}$\\
$G \leftarrow Gbasis(P)$\\
-- Assume a polynomial of form $\sum{a_k\tilde{x}^k}$\\
-- then require that\\
-- Reduce$(\sum{a_k\tilde{x}^k},G)=
\sum{a_kReduce(\tilde{x}^k,G)}=0$\\
$k \leftarrow 0$\\
-- If $G$ does not satify the termination theorem, the loop may be infinite\\
*do* \{
\begin{addmargin}{1em}
$p_k \leftarrow Reduce(\tilde{x}^k,G)$\\
*if* $\exists (a_0,...,a_k)\ne (0,...,0)$
such that $\sum_{j=0}^k{a_jp_j}=0$ *then*
\begin{addmargin}{1em}
*return*$(a_k^{-1}\cdot \sum_{j=0}^k{a_j\tilde{x}^j})$
\end{addmargin}
*else* $k \leftarrow k+1$ \}
\end{addmargin}
\end{addmargin}
*end*

*** Background

*** Example

* Complete Solutions of a System
[cite:@Gedd92] p 458\\
*procedure* Gr\"obnerSolve$(P)$
\begin{addmargin}{1em}
-- Given system $P \subset F[x]$ with finitely many solutions\\
-- find these solutions over an ``approprite'' extension of $F$\\
-- We store partially refined bases and partial roots in $Q$\\
$Q \leftarrow \{ [P,()] \}$\\
*for* $k$ *from* $n$ *by* -1 *to* 1 *do* \{
\begin{addmargin}{1em}
$S \leftarrow \emptyset$\\
-- Refined/extend each element of $Q$ one more level\\
*foreach* $[G,(\alpha_{k+1},...,\alpha_n)] \in Q$ *do* \{
\begin{addmargin}{1em}
$\tilde{G} \leftarrow 
\{ g(x_1,...,x_k,\alpha_{k+1},...,\alpha_n) : g \in G \}$\\
$\tilde{G} \leftarrow Gbasis(\tilde{G})$\\
$p \leftarrow Solve1(\tilde{G},x_k)$\\
-- The roots of $p$ in $x_k$ yield several new partial roots\\
*if* $p \ne 1$ *then*
\begin{addmargin}{1em}
$S \leftarrow S \cup 
\{[\tilde{G},(\alpha,\alpha_{k+1},...,\alpha_n)]: p(\alpha) = 0\}$ \}
\end{addmargin}
\end{addmargin}
$Q \leftarrow S$ \}
\end{addmargin}
$roots \leftarrow \emptyset$\\
*foreach* $[G,(\alpha_1,...,\alpha_n)] \in Q$ *do* \{
\begin{addmargin}{1em}
$roots \leftarrow roots \cup \{ (\alpha_1,...,\alpha_n)\}$ \}
\end{addmargin}
*return*$(roots)$
\end{addmargin}
*end*

*** Background

*** Example

* Solution using Lexicographic Gr\"obner Basis
[cite:@Gedd92] p 461\\
*procedure* LexSolve$(P)$
\begin{addmargin}{1em}
-- First, find a reduced Gr\"obner basis with respect to $<_L$\\
-- for the ideal generated by $P \subset F[x]$\\
$G \leftarrow Gbasis(P)$\\
$roots \leftarrow \emptyset$\\
-- If $P$ has finitely many solutions, we proceed to\\
-- solve the univariate polynomial in $x_n$\\
$p \leftarrow selectpoly(G \cap F[x_n])$\\
$roots \leftarrow roots \cup \{ (\alpha) : p(\alpha) = 0 \}$\\
-- Now, backsolve\\
*for* $k$ *from* $n-1$ *by* -1 *to* 1 *do* \{
\begin{addmargin}{1em}
$S \leftarrow \emptyset$\\
$G_k \leftarrow G \cup F[x_k,...,x_n]-F[x_{k+1},...,x_n]$\\
*foreach* $(\alpha_{k+1},...,\alpha_n) \in roots$ *do* \{
\begin{addmargin}{1em}
$\tilde{G} \leftarrow \{g(x_k,\alpha_{k+1},...,\alpha_n) : g \in G_k\}$\\
$\tilde{G} \leftarrow Gbasis(\tilde{G})$\\
$p \leftarrow selectpoly(\tilde{G} \cap F[x_k])$\\
*if* $p\ne 1$ *then*
\begin{addmargin}{1em}
$S \leftarrow S \cup \{ (\alpha,\alpha_{k+1},...,\alpha_n):p(\alpha)=0\}$\}
\end{addmargin}
$roots \leftarrow S$ \}
\end{addmargin}
\end{addmargin}
*return*$(roots)$
\end{addmargin}
*end*

*** Background

*** Example

* Hermite's Method for Rational Functions
[cite:@Gedd92] p 485\\
*procedure* HermiteReduction$(p,q,x)$
\begin{addmargin}{1em}
-- Given a rational function $p/q$ in $x$, this algorithm\\
-- uses Hermite's method to reduce $\int{p/q}$\\
-- Determine polynomial part of integral\\
poly\_part $\leftarrow quo(p,q)$\\
$r \leftarrow rem(p,q)$\\
-- Calculate the square-free factorization of $q$, returning a list\\
-- $q[1],...,q[k]$ of polynomials\\
$(q[1],...,q[k]) \leftarrow SquareFree(q)$\\
-- Calculate the partial fraction decomposition for $r/q$, returning\\
-- numerators $r[i,j]$ for $q[i]^j$\\
$r \leftarrow PartialFractions(r,q[1],...,q[k])$\\
rational\_part $\leftarrow 0$\\
integral\_part $\leftarrow 0$\\
*for* $i$ *from* 1 *to* $k$ *do* \{
\begin{addmargin}{1em}
integral\_part $\leftarrow$ integral\_part$+r[i,1]/q[i]$\\
*for* $j$ *from* 2 *to* $i$ *do* \{
\begin{addmargin}{1em}
$n \leftarrow j$\\
*while* $n>1$ *do* \{
\begin{addmargin}{1em}
solve$(s\cdot q[i]+t\cdot q[i]^\prime = r[i,n])$ for $s$ and $t$\\
$n \leftarrow n-1$\\
rational\_part $\leftarrow$ rational\_part-$t/n/q[i]^n$\\
$r[i,n] \leftarrow s+t^\prime/n$ \}
\end{addmargin}
integral\_part $\leftarrow$ integral\_part+$r[i,1]/q[i]$ \} \}
\end{addmargin}
\end{addmargin}
*return*(rational\_part$+\int$poly\_part$+\int$integral\_part)
\end{addmargin}
*end*

*** Background

*** Example

* Horowitz Reduction for Rational Functions
[cite:@Gedd92] p 490\\
*procedure* HorowitzReduction$(p,q,x)$
\begin{addmargin}{1em}
-- For a given rational function $p/q$ in $x$, this algorithm calculates\\
-- the reduction of $\int{p/q}$ into a polynomial part and logarithmic part\\
-- via Horowitz' algorithm\\
poly\_part $\leftarrow$ quo$(p,q)$\\
$p \leftarrow rem(p,q)$\\
$d \leftarrow GCD(q,q^\prime)$\\
$b \leftarrow quo(q,d)$\\
$m \leftarrow deg(b)$\\
$n \leftarrow deg(d)$\\
$a \leftarrow \sum_{i=0}^{m-1}{a[i]\cdot x^i}$\\
$c \leftarrow \sum_{i=0}^{n-1}{c[i]\cdot x^i}$\\
$r \leftarrow b\cdot c^\prime - 
c\cdotquo(b\cdot d^\prime,d)+d\cdot a$\\
*for* $i$ *from* 0 *to* $m+n-1$ *do*
\begin{addmargin}{1em}
$eqn[i] \leftarrow coeff(p,i)=coeff(r,i)$
\end{addmargin}
solve$(eqns,\{a[0],...,a[m-1],c[0],...,c[n-1]\})$\\
*return*$(\frac{c}{d}+\int$poly\_part$+\int\frac{a}{b})$
\end{addmargin}
*end*

*** Background

*** Example

* Rothstein/Trager Method
[cite:@Gedd92] p 499\\
*procedure* LogarithmicPartIntegral$(a,b,x)$
\begin{addmargin}{1em}
-- Given a rational function $a/b$ in $x$ with deg$(a) <$ deg$(b)$,\\
-- $b$ monic and square-free, we calculate $\int\frac{a}{b}$\\
$R(z) \leftarrow pp_x(res_x(a-z\cdot b^\prime,b))$\\
$(r_1(z),...,r_k(z)) \leftarrow factors(R(z))$\\
integral $\leftarrow 0$\\
*for* $i$ *from* 1 *to* $k$ *do* \{
\begin{addmargin}{1em}
$d \leftarrow deg(r_i(z))$\\
*if* $d=1$ *then* \{
\begin{addmargin}{1em}
$c \leftarrow solve(r_i(z)=0,z)$\\
$v \leftarrow GCD(a-c\cdot b^\prime,b)$\\
$v \leftarrow v/lcoeff(v)$\\
integral $\leftarrow$ integral $+c\cdotlog(v)$ \}
\end{addmargin}
*else* \{
\begin{addmargin}{1em}
-- Need to do GCD over algebraic number field\\
$v \leftarrow GCD(a-\alpha\cdot b^\prime,b)$\\
$v \leftarrow v/lcoeff(v)$\\
--   (where $\alpha - RootOf(r_i(z))$)\\
*if* $d=2$ *then* \{
\begin{addmargin}{1em}
-- Give answer in terms of radicals\\
$c \leftarrow solve(r_i(z)=0,z)$\\
*for* $j$ *from* 1 *to* 2 *do* \{
\begin{addmargin}{1em}
$v[j] \leftarrow substitute(\alpha=c[j],v)$\\
integral $\leftarrow$ integral $+c[j]\cdotlog(v[j])$\}\}
\end{addmargin}
\end{addmargin}
*else* \{
\begin{addmargin}{1em}
-- Need answer in RootOf notation\\
*for* $j$ *from* 1 *to* $d$ *do* \{
\begin{addmargin}{1em}
$v[j] \leftarrow substutite(\alpha=c[j],v)$\\
integral $\leftarrow$ integral$+ c[j]\cdotlog(v[j])$\\
-- (where $c[j]=RootOf(r_i(z))$) \} \} \} \}
\end{addmargin}
\end{addmargin}
\end{addmargin}
\end{addmargin}
*return*(integral)
\end{addmargin}
*end*

*** Background

*** Example

* Lazard/Rioboo/Trager Improvement
[cite:@Gedd92] p 506\\
*procedure* LogarithmicPartIntegral$(a,b,x)$
\begin{addmargin}{1em}
-- Given a rational function $a/b$ in $x$, with deg($a$) $<$ deg($b$)\\
-- $b$ monic and square-free, we calculate $\int a/b$\\
-- Calculate (via the subresultant algorithm)\\
$R(z) = res_x(a-z\cdot b^\prime,b)$\\
$S_i(x,z) =$ remainder of degree $i$ in $x$ in this computation\\
$(R_1(x),...,R_k(z)) \leftarrow SquareFree(R(z))$\\
-- Process nontrivial square-free factors in $R(z)$\\
integral $\leftarrow 0$\\
*for* $i$ *from* 1 *to* $k$ *with* $R_i(z)\ne 1$ *do* \{
\begin{addmargin}{1em}
-- Normalize to make results monic\\
$w(z) = lcoeff_x(S_i(x,z))$\\
$EEA(w(z),R_i(z); s(z),t(z))$\\
$S_i(x,z)= pp_z(rem(s(z)\cdot S_i(x,z),R_i(z)))$\\
-- Convert the $S_i(x,c)$ for $c$ a root of $R_i(z)$ into simpler form\\
-- (see LogarithmicPartIntegral on [cite:@Gedd92] p 499)\\
$(r_{i,1},...,r_{i,k_i}) \leftarrow factors(R_i(z))$\\
*for* $j$ *from* 1 *to* $k_i$ *do* \{
\begin{addmargin}{1em}
$d_j \leftarrow deg_z(r_{i,j}(z))$\\
*if* $d_j=1$ *then* \{
\begin{addmargin}{1em}
$c \leftarrow solve(r_{i,j}(z)=0,z)$\\
integral $\leftarrow$ integral$+c\cdot log(S_i(x,c))\}$
\end{addmargin}
*elseif* $d_j=2$ *then* \{ -- Give answers in terms of radicals\\
\begin{addmargin}{1em}
$c \leftarrow solve(r_{i,j}(z)=0,z)$\\
*for* $n$ *from* 1 *to* 2 *do* \{
\begin{addmargin}{1em}
integral $\leftarrow$ integral$+c[n]\cdot log(S_i(x,c[n]))$ \}\}
\end{addmargin}
\end{addmargin}
*else* \{ -- need answer in RootOf notatin
\begin{addmargin}{1em}
*for* $n$ *from* 1 *to* $d_j$ *do* \{
\begin{addmargin}{1em}
integral $\leftarrow$ integral+$c[n]\cdotlog(S_i(x,c[n]))$\\
-- (where $c[n]=RootOf(r_{i,j}(z)))$ \}\}\}\}
\end{addmargin}
\end{addmargin}
\end{addmargin}
\end{addmargin}
*return*(integral)
\end{addmargin}
*end*

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\cleardoublepage
\phantomsection
\addcontentsline{toc}{chapter}{Bibliography}
\bibliographystyle{axiom}
\bibliography{axiom}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\cleardoublepage
\phantomsection
\addcontentsline{toc}{chapter}{Index}
\printindex
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\end{document}
